set.seed(1234)
options(digits = 4)
x = rnorm(100,75,9)
mean(x)
var(x)
sd(x)
max(x)-min(x)
quantile(x,0.75)-quantile(x,0.25)
which.max(table(x))
quantile(x)
hist(x,probability = T)
boxplot(x,main = '箱线图',horizontal = T)
