set.seed(0)
data1 <- data.frame(rnorm(10))
set.seed(1)
data2 <- data.frame(rnorm(10,100,0.2))
set.seed(2)
data3 <- data.frame(rnorm(10,30,0.5))
data <- cbind(data1,data2,data3)
b1 <- (data[, 1] - min(data[, 1])) / (max(data[, 1]) - min(data[, 1]))
b2 <- (data[, 2] - min(data[, 2])) / (max(data[, 2]) - min(data[, 2]))
b3 <- (data[, 3] - min(data[, 3])) / (max(data[, 3]) - min(data[, 3]))
data_scatter <- cbind(b1, b2, b3)
names(data_scatter)=c('X1','X2','X3')
View(data_scatter)
