/**
 * Statistical Method Selector question bank (English) —— generated by scripts/generate-selector.mjs
 * from the very same rule table as the Chinese bank. Do not edit by hand.
 * To change the rules, edit the generator and run it again.
 */
export interface SelectorOption { text: string; detail?: string; next: number }
export interface SelectorResult {
  method: string
  why: string
  cond?: string[]
  note?: string
  criteria?: string[][]
  code?: string
  read?: string[]
  pit?: string[]
  c: { text: string; link: string }
}
export interface SelectorNode {
  id: number
  question?: string
  hint?: string
  options?: SelectorOption[]
  result?: SelectorResult
}
export const selectorTree: { nodes: SelectorNode[] } = {
  "nodes": [
    {
      "id": 1,
      "question": "How did the data you have come about?",
      "hint": "Choose the closest option. If you are unsure, start with “just want to describe it” — descriptive analysis cannot go wrong.",
      "options": [
        {
          "text": "Just want to see what these data look like",
          "detail": "No test intended yet — descriptive statistics first",
          "next": 100
        },
        {
          "text": "One group of subjects, to be compared with a known standard",
          "detail": "For example the mean height of 120 male students vs the national average",
          "next": 104
        },
        {
          "text": "The same subjects measured twice",
          "detail": "Before and after treatment, left and right eye, one specimen measured by two methods",
          "next": 110
        },
        {
          "text": "Two different groups of subjects",
          "detail": "Treatment group vs control group, with the two groups independent",
          "next": 116
        },
        {
          "text": "Three or more different groups of subjects",
          "detail": "Comparing three dose groups",
          "next": 122
        },
        {
          "text": "The same subjects measured three times or more",
          "detail": "Measured once each at 1 month, 3 months, and 6 months after surgery",
          "next": 128
        },
        {
          "text": "Follow-up data",
          "detail": "Two columns: how long the follow-up lasted and whether the outcome occurred",
          "next": 132
        },
        {
          "text": "Want to look at the relationship between two variables",
          "detail": "No grouping — just whether two measurements are related",
          "next": 136
        },
        {
          "text": "You have a diagnostic index and want to judge how accurate it is",
          "detail": "A gold-standard diagnosis plus a measured value of that index, for example whether s100b can identify brain injury",
          "next": 142
        },
        {
          "text": "The same subjects measured or judged repeatedly — do the results agree?",
          "detail": "Two doctors reading the same set of images, or two instruments measuring the same set of samples",
          "next": 145
        }
      ]
    },
    {
      "id": 100,
      "question": "What does the variable you want to analyze look like?",
      "hint": "This means the one variable you want to compare or describe, not every variable",
      "options": [
        {
          "text": "A specific number",
          "detail": "Height, blood pressure, white blood cell count, total scale score …",
          "next": 101
        },
        {
          "text": "Only two categories",
          "detail": "Male/female, alive/dead, positive/negative …",
          "next": 102
        },
        {
          "text": "Three or more categories",
          "detail": "ABO blood group, department, or ordered grades such as mild/moderate/severe",
          "next": 103
        }
      ]
    },
    {
      "id": 104,
      "question": "What does the variable you want to analyze look like?",
      "hint": "This means the one variable you want to compare or describe, not every variable",
      "options": [
        {
          "text": "A specific number",
          "detail": "Height, blood pressure, white blood cell count, total scale score …",
          "next": 105
        },
        {
          "text": "Only two categories",
          "detail": "Male/female, alive/dead, positive/negative …",
          "next": 108
        },
        {
          "text": "Three or more categories",
          "detail": "ABO blood group, department, or ordered grades such as mild/moderate/severe",
          "next": 109
        }
      ]
    },
    {
      "id": 105,
      "question": "Roughly what are the sample size and the shape of these data?",
      "hint": "If you are unsure, choose the first option — it gives you a safe method that does not rely on distributional assumptions",
      "options": [
        {
          "text": "Not sure / fewer than 40 per group / the plot shows clear skewness or extreme values",
          "detail": "This is the safest choice — it recommends methods that do not rely on distributional assumptions",
          "next": 106
        },
        {
          "text": "More than 40 per group, histogram roughly symmetric with no outliers",
          "detail": "",
          "next": 107
        },
        {
          "text": "More than 40 per group, but the distribution is clearly skewed",
          "detail": "",
          "next": 106
        }
      ]
    },
    {
      "id": 110,
      "question": "What does the variable you want to analyze look like?",
      "hint": "This means the one variable you want to compare or describe, not every variable",
      "options": [
        {
          "text": "A specific number",
          "detail": "Height, blood pressure, white blood cell count, total scale score …",
          "next": 111
        },
        {
          "text": "Only two categories",
          "detail": "Male/female, alive/dead, positive/negative …",
          "next": 114
        },
        {
          "text": "Three or more categories",
          "detail": "ABO blood group, department, or ordered grades such as mild/moderate/severe",
          "next": 115
        }
      ]
    },
    {
      "id": 111,
      "question": "Roughly what are the sample size and the shape of these data?",
      "hint": "If you are unsure, choose the first option — it gives you a safe method that does not rely on distributional assumptions",
      "options": [
        {
          "text": "Not sure / fewer than 40 per group / the plot shows clear skewness or extreme values",
          "detail": "This is the safest choice — it recommends methods that do not rely on distributional assumptions",
          "next": 112
        },
        {
          "text": "More than 40 per group, histogram roughly symmetric with no outliers",
          "detail": "",
          "next": 113
        },
        {
          "text": "More than 40 per group, but the distribution is clearly skewed",
          "detail": "",
          "next": 112
        }
      ]
    },
    {
      "id": 116,
      "question": "What does the variable you want to analyze look like?",
      "hint": "This means the one variable you want to compare or describe, not every variable",
      "options": [
        {
          "text": "A specific number",
          "detail": "Height, blood pressure, white blood cell count, total scale score …",
          "next": 117
        },
        {
          "text": "Only two categories",
          "detail": "Male/female, alive/dead, positive/negative …",
          "next": 120
        },
        {
          "text": "Three or more categories",
          "detail": "ABO blood group, department, or ordered grades such as mild/moderate/severe",
          "next": 121
        }
      ]
    },
    {
      "id": 117,
      "question": "Roughly what are the sample size and the shape of these data?",
      "hint": "If you are unsure, choose the first option — it gives you a safe method that does not rely on distributional assumptions",
      "options": [
        {
          "text": "Not sure / fewer than 40 per group / the plot shows clear skewness or extreme values",
          "detail": "This is the safest choice — it recommends methods that do not rely on distributional assumptions",
          "next": 118
        },
        {
          "text": "More than 40 per group, histogram roughly symmetric with no outliers",
          "detail": "",
          "next": 119
        },
        {
          "text": "More than 40 per group, but the distribution is clearly skewed",
          "detail": "",
          "next": 118
        }
      ]
    },
    {
      "id": 122,
      "question": "What does the variable you want to analyze look like?",
      "hint": "This means the one variable you want to compare or describe, not every variable",
      "options": [
        {
          "text": "A specific number",
          "detail": "Height, blood pressure, white blood cell count, total scale score …",
          "next": 123
        },
        {
          "text": "Only two categories",
          "detail": "Male/female, alive/dead, positive/negative …",
          "next": 126
        },
        {
          "text": "Three or more categories",
          "detail": "ABO blood group, department, or ordered grades such as mild/moderate/severe",
          "next": 127
        }
      ]
    },
    {
      "id": 123,
      "question": "Roughly what are the sample size and the shape of these data?",
      "hint": "If you are unsure, choose the first option — it gives you a safe method that does not rely on distributional assumptions",
      "options": [
        {
          "text": "Not sure / fewer than 40 per group / the plot shows clear skewness or extreme values",
          "detail": "This is the safest choice — it recommends methods that do not rely on distributional assumptions",
          "next": 124
        },
        {
          "text": "More than 40 per group, histogram roughly symmetric with no outliers",
          "detail": "",
          "next": 125
        },
        {
          "text": "More than 40 per group, but the distribution is clearly skewed",
          "detail": "",
          "next": 124
        }
      ]
    },
    {
      "id": 128,
      "question": "What does the variable you want to analyze look like?",
      "hint": "This means the one variable you want to compare or describe, not every variable",
      "options": [
        {
          "text": "A specific number",
          "detail": "Height, blood pressure, white blood cell count, total scale score …",
          "next": 129
        },
        {
          "text": "Only two categories",
          "detail": "Male/female, alive/dead, positive/negative …",
          "next": 130
        },
        {
          "text": "Three or more categories",
          "detail": "ABO blood group, department, or ordered grades such as mild/moderate/severe",
          "next": 131
        }
      ]
    },
    {
      "id": 132,
      "question": "Which question should the survival analysis answer?",
      "hint": "",
      "options": [
        {
          "text": "Estimate survival rates and look at the survival curve",
          "detail": "Draw the survival curve over time and find the median survival time",
          "next": 133
        },
        {
          "text": "Compare the survival curves of two groups",
          "detail": "For example which of two treatments gives the higher survival rate",
          "next": 134
        },
        {
          "text": "Look at the effect of several factors on survival",
          "detail": "Analyze age, stage, and treatment together",
          "next": 135
        }
      ]
    },
    {
      "id": 136,
      "question": "What type is each of these two variables?",
      "hint": "",
      "options": [
        {
          "text": "Both are specific numbers",
          "detail": "For example height and weight, age and blood pressure",
          "next": 137
        },
        {
          "text": "At least one is a categorical variable",
          "detail": "For example blood group and disease, sex and treatment effect",
          "next": 141
        }
      ]
    },
    {
      "id": 137,
      "question": "What is the relationship between these two numeric variables?",
      "hint": "",
      "options": [
        {
          "text": "It looks roughly like a straight line",
          "detail": "The points on the scatterplot follow a straight line",
          "next": 138
        },
        {
          "text": "They only increase or decrease together; it is not a straight line",
          "detail": "",
          "next": 139
        },
        {
          "text": "You want to use one to predict the other",
          "detail": "For example using height to predict vital capacity",
          "next": 140
        }
      ]
    },
    {
      "id": 142,
      "question": "What is this index used for?",
      "hint": "The same index used in different roles is evaluated with different measures",
      "options": [
        {
          "text": "Separating patients from non-patients",
          "detail": "A gold-standard diagnosis is available and you want to know how well the index discriminates",
          "next": 143
        },
        {
          "text": "Judging whether two measurements agree",
          "detail": "Not comparing differences but asking how well the measurement repeats — you can take the branch below",
          "next": 144
        }
      ]
    },
    {
      "id": 145,
      "question": "What type are the results of the repeated measurements or judgments?",
      "hint": "",
      "options": [
        {
          "text": "Categories with no order",
          "detail": "Positive/negative, several diagnostic categories, blood group",
          "next": 146
        },
        {
          "text": "Graded in order",
          "detail": "Scores from 1 to 5, mild/moderate/severe",
          "next": 147
        },
        {
          "text": "Specific numbers",
          "detail": "Blood pressure, total scale score, instrument reading",
          "next": 148
        },
        {
          "text": "Specific numbers, and you want to know how much the two methods differ and how consistently",
          "detail": "Besides the summary agreement measure, you want to see how large the systematic bias is",
          "next": 149
        }
      ]
    },
    {
      "id": 101,
      "result": {
        "method": "Mean ± SD, or median (IQR)",
        "why": "Describes the **average level** and the **spread** of a batch of quantitative data.",
        "cond": [
          "The variable is quantitative",
          "No group comparison is intended — you only want to describe"
        ],
        "note": "**Which one to use depends on the distribution**: roughly symmetric with no extreme values → mean ± SD; clearly skewed or with extreme values → median (IQR). Reporting both is also acceptable.",
        "code": "mean(x); sd(x)                  # mean ± SD\nmedian(x); IQR(x)               # median (interquartile range)\nquantile(x, c(0.25, 0.5, 0.75)) # the three quartiles",
        "read": [
          "If the mean and the median are far apart → the distribution is skewed, so report the median first",
          "If the SD is larger than the mean → the data are very spread out, or extreme values are present"
        ],
        "pit": [
          "Using mean ± SD to describe clearly skewed data — this hides the real distribution",
          "Reporting only the average and not the spread"
        ],
        "c": {
          "text": "Chapter 4. Describing Quantitative Data",
          "link": "/en/Health-statistics/04-describing-quantitative-data"
        }
      }
    },
    {
      "id": 102,
      "result": {
        "method": "Frequency + rate (proportion)",
        "why": "Describes the **frequency of occurrence** of a binary variable.",
        "cond": [
          "The variable has only two categories",
          "The denominator is the total number of observational units in which the event could occur"
        ],
        "note": "The numerator is the number of cases in which the event occurred, and the denominator is **all** observational units — not “the number of cases in which it did not occur”.",
        "code": "table(d$outcome)\nprop.table(table(d$outcome)) * 100   # percentage",
        "read": [
          "Check that the denominator is right — the denominator of a rate must be the number of people in whom the event could occur"
        ],
        "pit": [
          "Using a proportion as if it were a rate — see the “rate versus proportion” comparison table in Chapter 5"
        ],
        "c": {
          "text": "Chapter 5. Describing Qualitative Data",
          "link": "/en/Health-statistics/05-describing-qualitative-data"
        }
      }
    },
    {
      "id": 103,
      "result": {
        "method": "Frequency + proportion",
        "why": "Describes the **share of each part** of a multi-category variable.",
        "cond": [
          "The variable is categorical (nominal or ordinal)"
        ],
        "note": "**The proportions must add up to 100%**, and the parts trade off against one another, so a proportion cannot be used as an “occurrence rate”.",
        "code": "table(d$type)\nprop.table(table(d$type)) * 100",
        "read": [
          "The parts should add up to 100%; if they do not, the denominator is wrong"
        ],
        "pit": [
          "For ordinal data the levels should also be arranged **in order**, otherwise the trend from mild to severe is invisible"
        ],
        "c": {
          "text": "Chapter 5. Describing Qualitative Data",
          "link": "/en/Health-statistics/05-describing-qualitative-data"
        }
      }
    },
    {
      "id": 106,
      "result": {
        "method": "Wilcoxon signed-rank test (one sample)",
        "why": "One set of quantitative measurements compared with a known standard value, but the data **depart from normality, or contain extreme values, or come from a very small sample**.",
        "cond": [
          "There is only one group of subjects",
          "The variable is quantitative, but normality does not hold"
        ],
        "note": "Normality is not required; the price is **slightly lower power** (the same difference needs a larger sample to be detected).",
        "code": "wilcox.test(x, mu = 170)   # replace 170 with the standard value you are comparing against",
        "read": [
          "`V` is the sum of ranks of the positive differences",
          "`p-value`: compare it with α",
          "Look at `median(x)` rather than the mean — it goes better with a nonparametric method"
        ],
        "pit": [
          "Using it even when the data are in fact close to normal — power is lost for nothing",
          "When there are many tied values R prints a warning; do not read it as an error"
        ],
        "c": {
          "text": "Chapter 11. Nonparametric and Rank-Based Tests",
          "link": "/en/Health-statistics/11-nonparametric"
        }
      }
    },
    {
      "id": 107,
      "result": {
        "method": "One-sample t test",
        "why": "One set of quantitative measurements, compared with **a known standard value**.",
        "cond": [
          "There is only one group of subjects",
          "The variable is quantitative",
          "The data are approximately normal; with a small sample (n < 40) this must hold fairly strictly"
        ],
        "code": "t.test(x, mu = 170)      # replace 170 with the standard value you are comparing against",
        "read": [
          "`t` and `df` (degrees of freedom = n − 1)",
          "`p-value`: compare it with the significance level α",
          "`conf.int`: the 95% confidence interval for the difference between the mean and the standard value"
        ],
        "pit": [
          "Saying “the population mean equals the standard value” when you only failed to reject H₀ — you can only say that no difference was found",
          "With a large sample a small p value may only reflect the sample size, so look at the actual size of the mean difference"
        ],
        "c": {
          "text": "Chapter 8. t Tests",
          "link": "/en/Health-statistics/08-t-test"
        }
      }
    },
    {
      "id": 108,
      "result": {
        "method": "Binomial test",
        "why": "One binary variable compared with **a known rate**.",
        "cond": [
          "The variable has only two categories",
          "The question is whether the rate equals a particular value"
        ],
        "code": "binom.test(45, 200, p = 0.30)   # replace 45/200 with your counts and 0.30 with the known rate",
        "read": [
          "`p-value` comes from the exact method and is more reliable than the normal approximation",
          "`conf.int` is the confidence interval for the rate — with a small sample it is wide, and that is exactly the point"
        ],
        "pit": [
          "Using the normal approximation for the confidence interval of a rate with a small sample can give a negative lower limit — the exact method should be used"
        ],
        "c": {
          "text": "Chapter 6. Estimating Population Means and Rates",
          "link": "/en/Health-statistics/06-estimation"
        }
      }
    },
    {
      "id": 109,
      "result": {
        "method": "Goodness-of-fit chi-square test",
        "why": "One multi-category variable: whether the **observed frequencies** depart from a theoretical distribution.",
        "cond": [
          "The variable has several categories",
          "The expected frequency T is ≥ 5 in every category (otherwise categories must be combined)"
        ],
        "code": "chisq.test(table(d$type), p = c(0.5, 0.3, 0.2))   # replace with your hypothesized proportions; their number must equal the number of categories",
        "read": [
          "`X-squared` and `df` (degrees of freedom = number of categories − 1)",
          "`p-value`: compare it with α"
        ],
        "pit": [
          "Forcing the calculation when the expected frequencies are too small — R warns, and the categories then have to be combined"
        ],
        "c": {
          "text": "Chapter 10. Chi-Square Tests",
          "link": "/en/Health-statistics/10-chi-square"
        }
      }
    },
    {
      "id": 112,
      "result": {
        "method": "Wilcoxon signed-rank test (paired)",
        "why": "Paired data, but **the distribution of the differences is clearly non-normal**.",
        "cond": [
          "The two sets of measurements are paired one to one",
          "The differences are not normal"
        ],
        "code": "wilcox.test(x, y, paired = TRUE)",
        "read": [
          "`V` is the sum of ranks of the positive differences (it is not an effect size, so do not read it as a magnitude)",
          "`p-value`: compare it with α"
        ],
        "pit": [
          "When it is compared with the paired t test, the write-up must say which of the two was used rather than mixing them"
        ],
        "c": {
          "text": "Chapter 11. Nonparametric and Rank-Based Tests",
          "link": "/en/Health-statistics/11-nonparametric"
        }
      }
    },
    {
      "id": 113,
      "result": {
        "method": "Paired t test",
        "why": "The same subjects measured twice (or two paired sites), to test whether the **difference** between the two measurements is 0.",
        "cond": [
          "The two sets of measurements are paired one to one",
          "The **differences** are approximately normal (not each of the two measurements separately)"
        ],
        "note": "In essence the differences are treated as one set of data and a one-sample t test is run on them, so the degrees of freedom are **the number of pairs − 1**, not the total number of measurements − 2.",
        "code": "t.test(x, y, paired = TRUE)      # two vectors of equal length\n# Note: t.test(y ~ g, data = d, paired = TRUE) returns an error\n#      the formula interface is only interpreted as two independent samples,\n#      so paired data must be passed as two vectors",
        "read": [
          "`df` = number of pairs − 1",
          "`mean of the differences` is the mean difference — more worth looking at than the p value",
          "`conf.int` is the 95% confidence interval for the mean difference"
        ],
        "pit": [
          "**Treating a paired design as an independent-groups comparison** — the most common and the most damaging mistake; the p value comes out too large and the conclusion may reverse",
          "Using a paired t test when there is no pairing"
        ],
        "c": {
          "text": "Chapter 8. t Tests",
          "link": "/en/Health-statistics/08-t-test"
        }
      }
    },
    {
      "id": 114,
      "result": {
        "method": "McNemar's test (paired 2×2 table)",
        "why": "The same subjects measured twice, **with a yes/no result each time**; tests whether the positive rate changed between the two measurements.",
        "cond": [
          "Paired design",
          "The variable is binary",
          "**Only the two discordant cells are compared** (b and c)"
        ],
        "note": "This is **a different question** from comparing positive rates between two groups of people — that one uses an ordinary 2×2 chi-square test, and the two must not be mixed up.",
        "code": "m <- table(before, after)   # before / after are the same people's yes/no results on the two occasions\nmcnemar.test(m)",
        "read": [
          "Look only at the off-diagonal cells b and c",
          "For b + c ≥ 40 the uncorrected formula is used and for b + c < 40 the corrected one (R chooses automatically)"
        ],
        "pit": [
          "Using an ordinary chi-square test on paired data — this ignores the pairing and the conclusion may come out completely reversed"
        ],
        "c": {
          "text": "Chapter 10. Chi-Square Tests",
          "link": "/en/Health-statistics/10-chi-square"
        }
      }
    },
    {
      "id": 115,
      "result": {
        "method": "Not covered in this course",
        "why": "The combination you selected falls outside the 17 chapters covered on this site.",
        "cond": [],
        "note": "It is not that no method exists, but that these situations are not developed in this course. **Go back and re-check the study design you selected** (often the first step was the wrong one); if it still does not match, ask the course instructor or a statistician.",
        "read": [],
        "pit": [
          "Forcing the data into a method you happen to know — the most dangerous mistake in data analysis"
        ],
        "c": {
          "text": "Chapter 3. Experimental and Survey Design",
          "link": "/en/Health-statistics/03-study-design"
        }
      }
    },
    {
      "id": 118,
      "result": {
        "method": "Mann–Whitney U test (Wilcoxon rank-sum test)",
        "why": "Two independent groups, comparing a quantitative or **ordinal** variable, but the data are non-normal, contain extreme values, or come from a very small sample.",
        "cond": [
          "The two groups of subjects are independent",
          "A quantitative variable (non-normal) or an **ordinal variable**"
        ],
        "note": "What is compared is whether the values in one group tend to be larger than those in the other, not the difference between the means.",
        "code": "wilcox.test(value ~ group, data = d)",
        "read": [
          "`W` is the rank-sum statistic, **not an effect size**",
          "`p-value`: compare it with α",
          "Report it together with the medians of the two groups"
        ],
        "pit": [
          "Reporting `W` as “how big the difference is”",
          "Using it when the data are in fact close to normal — power is lost for nothing"
        ],
        "c": {
          "text": "Chapter 11. Nonparametric and Rank-Based Tests",
          "link": "/en/Health-statistics/11-nonparametric"
        }
      }
    },
    {
      "id": 119,
      "result": {
        "method": "Two-sample t test (Welch's)",
        "why": "Two **independent** groups of subjects, comparing the average level of a quantitative variable.",
        "cond": [
          "The two groups of subjects are independent (not the same people)",
          "The variable is quantitative",
          "The data are approximately normal, **or** each group has a fairly large sample (n ≥ 40 or so, by the central limit theorem)"
        ],
        "note": "**Using the R default (Welch) directly is recommended**: it does not require equal variances between the two groups and gives a more stable result. Only when a test for homogeneity of variance clearly supports it and the two sample sizes are similar does the pooled-variance version have a slight advantage.",
        "code": "t.test(value ~ group, data = d)                 # Welch, recommended\nt.test(value ~ group, data = d, var.equal = TRUE) # pooled variance, requires equal variances",
        "read": [
          "It is **normal** for `df` not to be a whole number — Welch’s degrees of freedom are computed",
          "`p-value`: compare it with α",
          "`estimate` gives the two group means; report them together with the p value"
        ],
        "pit": [
          "**Mistaking a paired design for an independent-groups comparison**",
          "Testing homogeneity of variance first and abandoning the t test when it fails — using Welch directly is simpler and more stable"
        ],
        "c": {
          "text": "Chapter 8. t Tests",
          "link": "/en/Health-statistics/08-t-test"
        }
      }
    },
    {
      "id": 120,
      "result": {
        "method": "2×2 chi-square test (the version depends on the conditions)",
        "why": "Two independent groups, comparing the rate of a **binary** variable.",
        "cond": [
          "The two groups of subjects are independent",
          "The variable is binary",
          "The total number of cases n and the smallest expected frequency T_min determine which version is used"
        ],
        "note": "How to choose among the three versions — this is where mistakes are most common:",
        "criteria": [
          [
            "n ≥ 40 and the expected frequency T ≥ 5 in every cell",
            "Use the dedicated formula without correction"
          ],
          [
            "n ≥ 40 but some cell has 1 ≤ T < 5",
            "Use the continuity correction"
          ],
          [
            "n < 40, or some cell has T < 1",
            "Switch to Fisher's exact test"
          ]
        ],
        "code": "tab <- table(d$group, d$outcome)\nchisq.test(tab)                  # R applies the continuity correction by default\nchisq.test(tab, correct = FALSE) # no correction\nfisher.test(tab)                 # exact test",
        "read": [
          "`X-squared` and `df` (always 1 for a 2×2 table)",
          "`p-value`: compare it with α",
          "When R warns that `Chi-squared approximation may be incorrect`, **switch to Fisher**"
        ],
        "pit": [
          "Ignoring R’s warning about the approximation and using chi-square anyway",
          "Working out the percentages the wrong way round — rates (across rows) and proportions (down columns)"
        ],
        "c": {
          "text": "Chapter 10. Chi-Square Tests",
          "link": "/en/Health-statistics/10-chi-square"
        }
      }
    },
    {
      "id": 121,
      "result": {
        "method": "R×C contingency-table chi-square test",
        "why": "Two or more independent groups, comparing a **nominal multi-category** variable, or any contingency table with more than 2 rows or columns.",
        "cond": [
          "The groups are independent",
          "The variable is nominal",
          "**No more than 1/5 of the cells have an expected frequency < 5**, and no cell may have T < 1"
        ],
        "note": "H₁ can only be stated as “**the group proportions are not all the same**”, never as “all the groups differ”. If the expected frequencies are too small, combine categories or switch to an exact test.",
        "code": "chisq.test(table(d$group, d$type))",
        "read": [
          "`df` = (number of rows − 1) × (number of columns − 1)",
          "`p-value`: compare it with α"
        ],
        "pit": [
          "Saying “all the groups differ” after a significant result — the result only says they are not all the same; specific comparisons need multiple comparisons with an adjusted α"
        ],
        "c": {
          "text": "Chapter 10. Chi-Square Tests",
          "link": "/en/Health-statistics/10-chi-square"
        }
      }
    },
    {
      "id": 124,
      "result": {
        "method": "Kruskal–Wallis H test",
        "why": "Three or more independent groups, comparing a quantitative (non-normal) or **ordinal** variable.",
        "cond": [
          "The groups are independent",
          "Quantitative but not normal, or **ordinal** to begin with"
        ],
        "code": "kruskal.test(value ~ group, data = d)",
        "read": [
          "`Kruskal-Wallis chi-squared` and `df` (number of groups − 1)",
          "`p-value`: compare it with α"
        ],
        "pit": [
          "Concluding straight after a significant result which two groups differ — multiple comparisons with an adjusted level are still needed"
        ],
        "c": {
          "text": "Chapter 11. Nonparametric and Rank-Based Tests",
          "link": "/en/Health-statistics/11-nonparametric"
        }
      }
    },
    {
      "id": 125,
      "result": {
        "method": "One-way ANOVA + multiple comparisons",
        "why": "Three or more **independent** groups of subjects, comparing the average level of a quantitative variable.",
        "cond": [
          "The groups are independent",
          "The variable is quantitative",
          "Each group is approximately normal",
          "**The variances are equal across groups**"
        ],
        "note": "**With three or more groups the t test must not be repeated** — three comparisons push the Type I error rate from 5% to about 14%. Only after ANOVA is significant do you run multiple comparisons (Tukey / SNK / Bonferroni).",
        "code": "fit <- aov(value ~ group, data = d)\nsummary(fit)        # first see whether there is an overall difference\nTukeyHSD(fit)       # then see which particular pairs differ",
        "read": [
          "`Pr(>F)` is the p value for the whole model — its being significant only says that the groups are not all the same",
          "The `p adj` of `TukeyHSD` is what gives the pairwise comparisons"
        ],
        "pit": [
          "Running multiple comparisons when the overall test is not significant",
          "Saying “all the groups differ” when the result only says they are not all the same"
        ],
        "c": {
          "text": "Chapter 9. Analysis of Variance",
          "link": "/en/Health-statistics/09-anova"
        }
      }
    },
    {
      "id": 126,
      "result": {
        "method": "R×C contingency-table chi-square test",
        "why": "Two or more independent groups, comparing a **nominal multi-category** variable, or any contingency table with more than 2 rows or columns.",
        "cond": [
          "The groups are independent",
          "The variable is nominal",
          "**No more than 1/5 of the cells have an expected frequency < 5**, and no cell may have T < 1"
        ],
        "note": "H₁ can only be stated as “**the group proportions are not all the same**”, never as “all the groups differ”. If the expected frequencies are too small, combine categories or switch to an exact test.",
        "code": "chisq.test(table(d$group, d$type))",
        "read": [
          "`df` = (number of rows − 1) × (number of columns − 1)",
          "`p-value`: compare it with α"
        ],
        "pit": [
          "Saying “all the groups differ” after a significant result — the result only says they are not all the same; specific comparisons need multiple comparisons with an adjusted α"
        ],
        "c": {
          "text": "Chapter 10. Chi-Square Tests",
          "link": "/en/Health-statistics/10-chi-square"
        }
      }
    },
    {
      "id": 127,
      "result": {
        "method": "R×C contingency-table chi-square test",
        "why": "Two or more independent groups, comparing a **nominal multi-category** variable, or any contingency table with more than 2 rows or columns.",
        "cond": [
          "The groups are independent",
          "The variable is nominal",
          "**No more than 1/5 of the cells have an expected frequency < 5**, and no cell may have T < 1"
        ],
        "note": "H₁ can only be stated as “**the group proportions are not all the same**”, never as “all the groups differ”. If the expected frequencies are too small, combine categories or switch to an exact test.",
        "code": "chisq.test(table(d$group, d$type))",
        "read": [
          "`df` = (number of rows − 1) × (number of columns − 1)",
          "`p-value`: compare it with α"
        ],
        "pit": [
          "Saying “all the groups differ” after a significant result — the result only says they are not all the same; specific comparisons need multiple comparisons with an adjusted α"
        ],
        "c": {
          "text": "Chapter 10. Chi-Square Tests",
          "link": "/en/Health-statistics/10-chi-square"
        }
      }
    },
    {
      "id": 129,
      "result": {
        "method": "Repeated-measures ANOVA",
        "why": "**The same subjects** measured three times or more at different time points (or under different conditions), comparing the quantitative variable across occasions.",
        "cond": [
          "Repeated measurements on the same subjects",
          "The variable is quantitative",
          "**Sphericity** holds (the correlation structure among the occasions)"
        ],
        "note": "It looks like a randomized block design but is not the same: in repeated measures **the same individual** is measured over and over, so the within-subject correlation has to be taken into account; when sphericity does not hold, a Greenhouse-Geisser correction is needed.",
        "code": "fit <- aov(value ~ factor(time) + Error(id/time), data = d)\nsummary(fit)",
        "read": [
          "Look at the p value in the `Error: id:time` stratum — that is the test of the time effect"
        ],
        "pit": [
          "Analyzing repeated-measures data as independent groups — this ignores the correlation and makes the p value far too small"
        ],
        "c": {
          "text": "Chapter 9. Analysis of Variance",
          "link": "/en/Health-statistics/09-anova"
        }
      }
    },
    {
      "id": 130,
      "result": {
        "method": "Not covered in this course",
        "why": "The combination you selected falls outside the 17 chapters covered on this site.",
        "cond": [],
        "note": "It is not that no method exists, but that these situations are not developed in this course. **Go back and re-check the study design you selected** (often the first step was the wrong one); if it still does not match, ask the course instructor or a statistician.",
        "read": [],
        "pit": [
          "Forcing the data into a method you happen to know — the most dangerous mistake in data analysis"
        ],
        "c": {
          "text": "Chapter 3. Experimental and Survey Design",
          "link": "/en/Health-statistics/03-study-design"
        }
      }
    },
    {
      "id": 131,
      "result": {
        "method": "Friedman test (rank test for a randomized block design)",
        "why": "The same subjects measured three times or more, but the variable is **ordinal**, or the quantitative data are clearly non-normal.",
        "cond": [
          "Repeated measurements on the same subjects",
          "An ordinal variable, or normality does not hold"
        ],
        "code": "friedman.test(y ~ time | id, data = d)",
        "read": [
          "`Friedman chi-squared` and `df`",
          "`p-value`: compare it with α"
        ],
        "pit": [
          "Getting the block (individual) factor wrong — the block variable must correctly identify the same individual"
        ],
        "c": {
          "text": "Chapter 11. Nonparametric and Rank-Based Tests",
          "link": "/en/Health-statistics/11-nonparametric"
        }
      }
    },
    {
      "id": 133,
      "result": {
        "method": "Kaplan–Meier estimate of the survival curve",
        "why": "Follow-up data: **estimating** how the survival rate changes over time (and giving the median survival time).",
        "cond": [
          "There are two columns: the follow-up time and whether the outcome occurred",
          "**Censoring** is present (loss to follow-up, or still alive when the study ends)"
        ],
        "note": "**Censoring is not missingness**: a censored subject was genuinely alive up to that point, and that information must be used rather than discarded as a missing value.",
        "code": "library(survival)\nfit <- survfit(Surv(time, status) ~ group, data = d)\nplot(fit, col = 1:2)\nsummary(fit)",
        "read": [
          "Each **step down** on the curve marks a time at which an event occurred",
          "The median survival time is the time at which the curve drops to 0.5",
          "Censored observations are marked with “+”"
        ],
        "pit": [
          "Discarding censored observations as if they were missing — this overestimates the death rate",
          "Comparing the curves directly when the two groups have very different follow-up ranges"
        ],
        "c": {
          "text": "Chapter 14. Survival Analysis",
          "link": "/en/Health-statistics/14-survival-analysis"
        }
      }
    },
    {
      "id": 134,
      "result": {
        "method": "Log-rank test",
        "why": "Follow-up data: whether **the survival curves of two (or more) groups** differ.",
        "cond": [
          "Follow-up data for two or more groups",
          "The survival curves are **roughly proportional** (when they are not, the log-rank test has low power)"
        ],
        "code": "survdiff(Surv(time, status) ~ group, data = d)",
        "read": [
          "`Chisq` and `df`",
          "`p`: compare it with α"
        ],
        "pit": [
          "Using the log-rank test when the curves clearly cross — it may fail to detect a difference, so consider splitting the time axis or using another test"
        ],
        "c": {
          "text": "Chapter 14. Survival Analysis",
          "link": "/en/Health-statistics/14-survival-analysis"
        }
      }
    },
    {
      "id": 135,
      "result": {
        "method": "Cox proportional hazards regression",
        "why": "Follow-up data: the effect of **several factors together** on survival time.",
        "cond": [
          "Follow-up time and outcome are available",
          "The **proportional hazards assumption** holds (each factor’s effect does not change over time)"
        ],
        "code": "fit <- coxph(Surv(time, status) ~ age + sex, data = d)\nsummary(fit)      # exp(coef) is the HR\ncox.zph(fit)      # test the proportional hazards assumption",
        "read": [
          "`exp(coef)` is the **HR (hazard ratio)**",
          "HR = 1.5 means the hazard is 1.5 times that of the reference group",
          "`cox.zph` with p < 0.05 → the proportional hazards assumption fails and the model must be changed"
        ],
        "pit": [
          "Treating the HR as a ratio of survival rates — it is a ratio of **hazard rates**",
          "Drawing conclusions without testing the proportional hazards assumption"
        ],
        "c": {
          "text": "Chapter 14. Survival Analysis",
          "link": "/en/Health-statistics/14-survival-analysis"
        }
      }
    },
    {
      "id": 138,
      "result": {
        "method": "Pearson correlation analysis",
        "why": "Two quantitative variables: whether there is a **linear** relationship between them and how strong it is.",
        "cond": [
          "Both variables are quantitative",
          "**Bivariate normality** (the joint distribution of the two variables is approximately normal)",
          "The relationship is roughly a straight line"
        ],
        "code": "cor(x, y)\ncor.test(x, y)          # with a test and a confidence interval\nplot(x, y)              # always draw the scatterplot first",
        "read": [
          "`r` lies between −1 and 1; the sign gives the direction and the absolute value the strength",
          "`p-value` only says that r is not 0; it does not mean the relationship is strong",
          "**Always draw the scatterplot first** — r can be pulled off course by a few points"
        ],
        "pit": [
          "Looking only at r without a scatterplot — Anscombe’s quartet is the counterexample: four completely different data sets all give r = 0.816",
          "Taking a large absolute value of r as proof that the correlation is “very strong”"
        ],
        "c": {
          "text": "Chapter 12. Bivariate Association",
          "link": "/en/Health-statistics/12-bivariate-association"
        }
      }
    },
    {
      "id": 139,
      "result": {
        "method": "Spearman's rank correlation",
        "why": "Two variables of which **at least one is quantitative and non-normal**, or **ordinal**: whether there is a **monotone** relationship between them.",
        "cond": [
          "The two variables are quantitative (non-normal) or ordinal",
          "The relationship is monotone (as one increases the other increases or decreases; it need not be a straight line)"
        ],
        "code": "cor(x, y, method = \"spearman\")\ncor.test(x, y, method = \"spearman\")",
        "read": [
          "`rho` is r_s, also between −1 and 1",
          "It is not sensitive to extreme values — that is its advantage"
        ],
        "pit": [
          "Reporting r_s and the Pearson r interchangeably — they measure different things (one monotone, one linear)"
        ],
        "c": {
          "text": "Chapter 12. Bivariate Association",
          "link": "/en/Health-statistics/12-bivariate-association"
        }
      }
    },
    {
      "id": 140,
      "result": {
        "method": "Simple linear regression",
        "why": "One quantitative variable is to be **predicted or explained by another quantitative variable**.",
        "cond": [
          "The dependent variable is quantitative",
          "The relationship between the independent and the dependent variable is roughly linear",
          "The residuals are roughly normal with equal variance (checked with residual plots)"
        ],
        "note": "**Correlation and regression ask two different things**: correlation asks whether there is a relationship and how strong it is (neither variable is primary); regression asks whether x can be used to predict y (which one is the independent variable matters).",
        "code": "fit <- lm(y ~ x, data = d)\nsummary(fit)     # coefficients, t tests, R²\nplot(fit)        # the four diagnostic plots — you must look at them",
        "read": [
          "In `Estimate`, `(Intercept)` is the intercept and `x` is the slope",
          "`R²` is how much of the variation the model explains",
          "In `plot(fit)` the 1st and 3rd plots check linearity and equal variance, and the 2nd checks normality"
        ],
        "pit": [
          "Reporting results without drawing the diagnostic plots",
          "Taking a large R² to mean the predictions must be accurate",
          "Extrapolating beyond the range of the data"
        ],
        "c": {
          "text": "Chapter 13. Simple Linear Regression",
          "link": "/en/Health-statistics/13-linear-regression"
        }
      }
    },
    {
      "id": 141,
      "result": {
        "method": "Chi-square test of independence + odds ratio (OR) / relative risk (RR)",
        "why": "Two categorical variables: whether they are **associated**, and **how strong** the association is.",
        "cond": [
          "Both variables are categorical",
          "The expected-frequency conditions for the chi-square test (the same criteria as the 2×2 table)"
        ],
        "note": "**The chi-square test gives the P value (whether there is an association) and the OR/RR gives the strength (how strong it is)** — both must be reported. A cohort study allows the RR; a case-control study allows only the OR.",
        "code": "tab <- table(d$exposure, d$outcome)   # two categorical variables\nchisq.test(tab)\n# For a 2×2 table work out the OR by hand as (a*d)/(b*c), or use epitools::oddsratio()",
        "read": [
          "`p-value`: compare it with α to judge whether there is an association",
          "OR = 1 means no association; > 1 positive, < 1 negative",
          "The OR is always farther from 1 than the RR — when the rate is not low the two differ markedly"
        ],
        "pit": [
          "Interpreting the OR as if it were the RR",
          "Looking only at the P value and not at the OR — with a large sample even a very small OR can be “significant”"
        ],
        "c": {
          "text": "Chapter 12. Bivariate Association",
          "link": "/en/Health-statistics/12-bivariate-association"
        }
      }
    },
    {
      "id": 143,
      "result": {
        "method": "ROC curve and AUC",
        "why": "A gold-standard diagnosis and a measured value of an index being evaluated: how well that index **separates patients from non-patients**.",
        "cond": [
          "Every subject has a gold-standard diagnosis (diseased / not diseased)",
          "The index under evaluation was also measured on the same subject"
        ],
        "note": "**What the AUC really means**: the probability that, if one patient and one non-patient are drawn at random, the patient has the higher value of the index. It is therefore independent of the index’s scale, units, and skewness.\n\n**The threshold should be decided by clinical cost, not by an algorithm**: for conditions where a missed diagnosis is serious (ectopic pregnancy, HIV screening), fix the sensitivity first and then choose the threshold.",
        "code": "library(pROC)\nr <- roc(金标准, 指标值, levels = c(\"disease-free\", \"diseased\"))\nauc(r)          # discrimination\nci.auc(r)       # always report the confidence interval\n\n# Choose the threshold by the Youden index (largest sensitivity + specificity - 1)\ncoords(r, \"best\", best.method = \"youden\",\n       ret = c(\"threshold\", \"sensitivity\", \"specificity\"))\nplot(r, print.auc = TRUE, print.thres = \"best\")",
        "read": [
          "The `AUC` and its 95% confidence interval",
          "The **sensitivity** and **specificity** at the chosen threshold",
          "Report LR+ / LR− as well when you can (they are comparable at both ends)"
        ],
        "pit": [
          "**Using the positive predictive value to compare two tests** — it changes with prevalence, so it can simply not be compared across two populations",
          "Reporting only the AUC and not the threshold — the AUC averages over all thresholds and cannot be put to clinical use",
          "**Choosing the threshold on the same data that are then used to report performance** — optimistic bias; the threshold must be validated on a separate set of data",
          "Dismissing an “AUC of 0.73” as merely “fair discrimination” and leaving it at that — you should say clearly whether it is usable in practice"
        ],
        "c": {
          "text": "Diagnostic Test Evaluation (ROC and AUC)",
          "link": "/en/Health-statistics/diagnostic-test"
        }
      }
    },
    {
      "id": 144,
      "result": {
        "method": "ICC, the intraclass correlation coefficient (agreement for quantitative data)",
        "why": "The same subjects measured repeatedly, where the result is **a number** (two instruments, or two doctors, measuring the same quantity): do the measurements agree?",
        "cond": [
          "Every subject was measured twice or more",
          "The measurement is a quantitative variable"
        ],
        "note": "**The ICC is a family of measures, not a single one.** Its form has to be chosen according to three things, and stated: the **model** (two-way random / two-way mixed), the **type** (single measurement / mean of $k$ measurements), and the **definition** (absolute agreement / consistency).\n\n**To decide whether two instruments can be interchanged, absolute agreement must be used**: the consistency definition, which cares only about the ordering, allows a constant systematic offset between raters (if A always scores 3 points higher than B, the ICC is still 1).",
        "code": "library(psych)\nICC(d)$results[, c(\"type\", \"ICC\", \"lower bound\", \"upper bound\")]\n\n# or\nlibrary(irr)\nicc(d, model = \"twoway\", type = \"agreement\", unit = \"single\")  # ICC(2,1)\nicc(d, model = \"twoway\", type = \"agreement\", unit = \"average\") # ICC(2,k)",
        "read": [
          "The `ICC` point estimate **and its 95% confidence interval** (grade it by the interval, not by the point estimate)",
          "How far apart ICC(2,1) and ICC(2,k) are for the same data",
          "The mean squares MSR / MSC / MSE — MSC larger than MSR means who is rating matters more than who is being rated"
        ],
        "pit": [
          "**Using the Pearson correlation coefficient to assess agreement** — add a constant to one whole set of values and the correlation does not move at all, even though the agreement is already gone",
          "Reporting an ICC without stating the model/type/definition — the same data can differ severalfold",
          "Looking at the point estimate and not the confidence interval — with a point estimate of 0.93 but an interval of 0.88–0.97 you can only say “somewhere between good and very good”",
          "Drawing conclusions from fewer than 30 subjects or fewer than 3 raters — the confidence interval is then too wide to be of any use"
        ],
        "c": {
          "text": "Agreement and Reliability (Kappa and ICC)",
          "link": "/en/Health-statistics/agreement-reliability"
        }
      }
    },
    {
      "id": 146,
      "result": {
        "method": "Kappa coefficient (agreement for categorical data)",
        "why": "The same subjects **judged repeatedly** (twice, or by two raters), where the judgment is a **nominal category**: do the two judgments agree?",
        "cond": [
          "Every subject was judged twice or more",
          "The judgment is a categorical variable and the categories **have no order**"
        ],
        "note": "**Kappa has already removed the part that agrees by chance**, so it is much stricter than the agreement rate: with an observed agreement of 90% the kappa may be only 0.44.\n\n**When you report kappa, report the observed agreement and the marginal distributions with it**, otherwise the reader cannot tell whether a low kappa means genuine disagreement or is caused by very skewed category distributions.",
        "code": "library(irr)\n# Between two raters\nkappa2(d[, c(\"评定者1\", \"评定者2\")])\n# Among several raters\nkappam.fleiss(d)\n\n# To see the agreement rate (kappa has to be reported together with it)\nmean(d$评定者1 == d$评定者2)",
        "read": [
          "`Kappa`: the agreement after chance agreement has been removed",
          "`z` and `p-value`: whether kappa is significantly greater than 0 (**this does not mean kappa is high enough**)",
          "The observed agreement $P_o$"
        ],
        "pit": [
          "**Computing a weighted kappa for nominal categories** — blood group and diagnostic category have no order, and numbering them invents information that does not exist",
          "Treating the kappa bands as a pass mark (0.61 or above counts as good) — the source says clearly that they are only descriptive labels",
          "Reporting kappa without $P_o$ — when the marginal distributions are very skewed the kappa is naturally low (the kappa paradox)",
          "Comparing kappas computed with different numbers of raters — a kappa between two raters and one among all raters are not the same thing"
        ],
        "c": {
          "text": "Agreement and Reliability (Kappa and ICC)",
          "link": "/en/Health-statistics/agreement-reliability"
        }
      }
    },
    {
      "id": 147,
      "result": {
        "method": "Weighted kappa (agreement for ordinal data)",
        "why": "The repeated judgments **have a graded order** (grades 1–5, mild/moderate/severe), and “off by 1 grade” and “off by 4 grades” should not be treated alike.",
        "cond": [
          "Every subject was judged twice or more",
          "The judgment is an ordinal variable"
        ],
        "note": "Weighted kappa gives different weights to different degrees of disagreement: with **linear weights** the weight decreases linearly with the difference in grades, while **quadratic weights** penalize large disagreements harder and usually give a larger value.\n\n**The type of weight must be stated** — the same data give 0.19 with linear weights and 0.30 with quadratic weights, and without saying which was used the values cannot be compared.",
        "code": "library(irr)\n# In irr the linear weights are called \"equal\" and the quadratic weights \"squared\"\nkappa2(d[, c(\"评定者1\", \"评定者2\")], weight = \"equal\")    # linear\nkappa2(d[, c(\"评定者1\", \"评定者2\")], weight = \"squared\")  # quadratic",
        "read": [
          "The weighted `Kappa` (**always state whether it is linear or quadratic**)",
          "Report the unweighted kappa as well, which shows how much is lost by treating the grades as nominal",
          "The observed agreement"
        ],
        "pit": [
          "Not stating the type of weight — linear and quadratic weights can differ by a factor of two",
          "Treating ordinal data as nominal — the kappa is then seriously underestimated",
          "Conversely, weighting **nominal** categories — an even more serious error"
        ],
        "c": {
          "text": "Agreement and Reliability (Kappa and ICC)",
          "link": "/en/Health-statistics/agreement-reliability"
        }
      }
    },
    {
      "id": 148,
      "result": {
        "method": "ICC, the intraclass correlation coefficient (agreement for quantitative data)",
        "why": "The same subjects measured repeatedly, where the result is **a number** (two instruments, or two doctors, measuring the same quantity): do the measurements agree?",
        "cond": [
          "Every subject was measured twice or more",
          "The measurement is a quantitative variable"
        ],
        "note": "**The ICC is a family of measures, not a single one.** Its form has to be chosen according to three things, and stated: the **model** (two-way random / two-way mixed), the **type** (single measurement / mean of $k$ measurements), and the **definition** (absolute agreement / consistency).\n\n**To decide whether two instruments can be interchanged, absolute agreement must be used**: the consistency definition, which cares only about the ordering, allows a constant systematic offset between raters (if A always scores 3 points higher than B, the ICC is still 1).",
        "code": "library(psych)\nICC(d)$results[, c(\"type\", \"ICC\", \"lower bound\", \"upper bound\")]\n\n# or\nlibrary(irr)\nicc(d, model = \"twoway\", type = \"agreement\", unit = \"single\")  # ICC(2,1)\nicc(d, model = \"twoway\", type = \"agreement\", unit = \"average\") # ICC(2,k)",
        "read": [
          "The `ICC` point estimate **and its 95% confidence interval** (grade it by the interval, not by the point estimate)",
          "How far apart ICC(2,1) and ICC(2,k) are for the same data",
          "The mean squares MSR / MSC / MSE — MSC larger than MSR means who is rating matters more than who is being rated"
        ],
        "pit": [
          "**Using the Pearson correlation coefficient to assess agreement** — add a constant to one whole set of values and the correlation does not move at all, even though the agreement is already gone",
          "Reporting an ICC without stating the model/type/definition — the same data can differ severalfold",
          "Looking at the point estimate and not the confidence interval — with a point estimate of 0.93 but an interval of 0.88–0.97 you can only say “somewhere between good and very good”",
          "Drawing conclusions from fewer than 30 subjects or fewer than 3 raters — the confidence interval is then too wide to be of any use"
        ],
        "c": {
          "text": "Agreement and Reliability (Kappa and ICC)",
          "link": "/en/Health-statistics/agreement-reliability"
        }
      }
    },
    {
      "id": 149,
      "result": {
        "method": "Bland–Altman agreement analysis",
        "why": "You want to know **how much two measurement methods differ and how consistently** — the ICC gives only a summary number and hides the size and shape of the bias.",
        "cond": [
          "The same subjects measured by two methods (or on two occasions)",
          "The measurement is a quantitative variable"
        ],
        "note": "Plot the mean of the two methods on the horizontal axis and their difference on the vertical axis: the **mean difference** is the systematic bias, and **mean difference ± 1.96 × SD of the differences** gives the limits of agreement.\n\n**It complements the ICC**: the ICC answers whether subjects can be distinguished, while Bland–Altman answers how much the methods differ and whether that difference is stable. Reporting both is clearest.",
        "code": "m <- (d$方法1 + d$方法2) / 2      # horizontal axis: mean of the two methods\ndiff <- d$方法1 - d$方法2          # vertical axis: difference between the two methods\nplot(m, diff, ylim = c(-1, 1) * max(abs(diff)) * 1.5,\n     xlab = \"Mean of the two methods\", ylab = \"Difference between the two methods\")\nabline(h = mean(diff), col = \"blue\")             # bias\nabline(h = mean(diff) + c(-1, 1) * 1.96 * sd(diff), col = \"red\", lty = 2)",
        "read": [
          "`mean(diff)`: the systematic bias (close to 0 in the ideal case)",
          "The limits of agreement: bias ± 1.96 × SD of the differences",
          "The shape of the scatter: whether there is a trend with the mean (proportional bias)"
        ],
        "pit": [
          "Looking only at whether the bias is 0 and not at how wide the limits are — a bias of 0 with very wide limits still means the two methods cannot be interchanged",
          "Applying ±1.96 × SD when the differences are clearly non-normal — the coverage of the limits is then wrong",
          "Using a correlation coefficient instead — a correlation shows nothing at all about systematic bias"
        ],
        "c": {
          "text": "Agreement and Reliability (Kappa and ICC)",
          "link": "/en/Health-statistics/agreement-reliability"
        }
      }
    }
  ]
}
