---
layout: doc
title: 10-卡方检验
---

# 第 10 章　卡方检验

> 前面几章比的是均数——身高、血压、血糖，都是能算出大小的定量指标。这一章换一个对象：当研究结果只能**分类清点个数**（有效/无效、阳性/阴性、A/B/O/AB 型血），要比较**率**或**构成比**、判断**两个分类变量有没有关联**，用的就是 $\chi^2$ 检验。一句话说清它的思路：**看实际频数 $A$ 与理论频数 $T$ 差得远不远**。

## 这一章要解决什么

医学研究里大量结局是「是/否」两分或几个类别，没法算均数：

- 两种药各治 100 人，有效率 80% 和 70%，这 10 个百分点是真的有差别，还是碰巧抽到的两批人不一样？
- 三种药的有效率 90%、80%、30%，能不能说「三种药疗效都不相同」？
- 同一个人先做甲法检查、再做乙法检查，两次阳性率 80% 和 60%，两种方法到底有没有差别？
- 血型分布和某种疾病有没有关系？某个基因的异常表达率是否随临床分期升高而升高？
- 某地 10 岁男孩的身高分布，符不符合正态分布？

这几问的**资料类型**互不相同（完全随机设计的两组、多组、自身配对、两变量交叉分类、频数分布），但都可以用同一个统计量去回答，因为这个统计量只管一件事：**观察到的格子频数，与「没有差别 / 没有关联」时应该出现的频数，吻合得怎么样**。本章就是把这套方法拆开讲清楚，并且在最后给出**什么时候能算、什么时候必须换方法**的判据——这一点比公式本身更重要。

<TrackList :tasks="['说得出 χ² 检验在比较什么', '会算理论频数 T 并定出自由度', '拿到四格表能判断该用专用公式、校正公式还是 Fisher', '知道多个率比较拒绝 H0 之后还要做两两比较', '认得出配对资料、会用 McNemar 检验', '说得清 χ² 检验的三类适用条件']" />

## 核心概念

### $\chi^2$ 分布与 $\chi^2$ 检验的基本思想

**$\chi^2$ 分布**是这样定义的：若有 $\nu$ 个相互独立、都服从标准正态分布 $N(0,1)$ 的随机变量 $Z_1, Z_2, \dots, Z_\nu$，则

$$\chi^2 = Z_1^2 + Z_2^2 + \cdots + Z_\nu^2$$

服从**自由度**为 $\nu$ 的 $\chi^2$ 分布。它的形状有几个特点，做题时会直接用到：

- 取值**恒为非负数**（平方和当然不可能是负的），所以 $\chi^2$ 分布的图形只有右半边；
- **右偏（正偏态）**：$\nu$ 越小偏得越厉害，$\nu$ 增大时逐渐变得对称，$\nu \to \infty$ 时近似正态；
- 一个分布只由 $\nu$ 决定，$\nu$ 变了就是另一个分布；
- **可加性**：若 $X \sim \chi^2_{\nu_1}$ 与 $Y \sim \chi^2_{\nu_2}$ 独立，则 $X + Y \sim \chi^2_{\nu_1 + \nu_2}$。这条性质后面讲 $\chi^2$ 分解（线性趋势检验）时会用到。

界值记作 $\chi^2_{\alpha,\nu}$，意思是「右侧尾部面积为 $\alpha$ 时的分界点」。$\nu = 1$、$\alpha = 0.05$ 时 $\chi^2_{0.05,1} = 3.84$——这是本章出现频率最高的一个数字，最好记住。

**为什么分类资料能用它做检验？** 对某个格子，若把 $T$ 看成该格频数的期望，$A$ 是实际观测，那么 $(A - T)/\sqrt{T}$ 就近似是一个标准正态变量（计数的方差约等于其期望）。把每个格子的这个量**平方后求和**，按上面的定义，得到的正是 $\chi^2$ 统计量：

$$\chi^2 = \sum \frac{(A - T)^2}{T}$$

这就是 $\chi^2$ 检验的**基本公式**。它的含义非常直白：**每个格子偏离期望的程度，按期望大小加权（除法），再统统平方加起来**。$A$ 与 $T$ 吻合得好，每一项都小，$\chi^2$ 就小；某一格偏得离谱，平方放大会把它顶上去。

自由度是

$$\nu = (R-1)(C-1)$$

$R$ 是行数、$C$ 是列数。这个式子可以这样理解：一共有 $RC$ 个格子，每个格子贡献一个平方项，本来自由度是 $RC$；但理论频数是用**行合计与列合计**算出来的（相当于估了 $R + C - 1$ 个边际参数），每估一个参数就少一个自由度，于是 $RC - (R + C - 1) = (R-1)(C-1)$。

关于检验方向有一个容易绕晕的点：备择假设写的是「不等」（$\pi_1 \ne \pi_2$），但 **$\chi^2$ 检验永远是单侧检验**。原因是统计量已经取了平方，$A$ 比 $T$ 大很多或小很多都会让 $\chi^2$ 变大，两侧的偏离被自动并到了分布的右尾。所以查表时只查上侧界值，从来不用把 $P$ 乘 2。

### 理论频数 $T$：$H_0$ 成立时「应该」每个格子有多少人

实际频数 $A$ 是数出来的，理论频数 $T$ 是**算出来的**，算法只有一条：

$$T_{RC} = \frac{n_R \, n_C}{n}$$

$n_R$ 是第 $R$ 行的行合计，$n_C$ 是第 $C$ 列的列合计，$n$ 是总例数。它背后的道理是：**$H_0$ 说各组的总体率相同，那么大家都应该等于合计率**，于是每格的理论人数就是「这一组有多少人」乘上「合计率」。

举个能算的例子。某研究比较两种方案，甲方案 60 人中 45 人有效，乙方案 40 人中 20 人有效：

| | 有效 | 无效 | 合计 |
| --- | --- | --- | --- |
| 甲方案 | 45 ($A$) | 15 | 60 |
| 乙方案 | 20 | 20 | 40 |
| 合计 | 65 | 35 | 100 |

合计有效率是 $65/100 = 65\%$。若两方案总体有效率相同，都该是 65%，那么甲方案 60 人里理论上应该有 $60 \times 65\% = 39$ 人有效，乙方案 40 人里应该有 $40 \times 65\% = 26$ 人有效。用公式验一下：$T_{11} = 60 \times 65 / 100 = 39$，$T_{21} = 40 \times 65 / 100 = 26$，一致。四个理论频数分别是 39、21、26、14。

代入基本公式：

$$\chi^2 = \frac{(45-39)^2}{39} + \frac{(15-21)^2}{21} + \frac{(20-26)^2}{26} + \frac{(20-14)^2}{14} = 6.593$$

$\nu = (2-1)(2-1) = 1$。查 $\chi^2$ 界值表，$6.593 > 3.84$，$P < 0.05$，按 $\alpha = 0.05$ 水准拒绝 $H_0$，可认为两种方案的有效率不同。下面会看到，用四格表的专用公式算出来是同一个数。

::: warning 理论频数不等于观察到的行、列比例
$T$ 是 $H_0$ 成立**假设下**的期望人数，只能算不能观察。「实际频数」和「理论频数」这两个词最容易混：$A$ 是你数出来的，$T$ 是你根据合计率推出来的。判断该用哪个公式（见下文判据表）看的也是 $T$，不是 $A$。
:::

### 四格表资料的 $\chi^2$ 检验

**四格表**（2×2 列联表）是最常用的情形：分组变量两个水平、结局变量两个水平，表内只有 4 个基本数据 $a$、$b$、$c$、$d$，行合计、列合计、总例数、率全都能从这 4 个数推出来。基本公式虽然通用，但逐格算 $T$ 再逐格算平方挺烦，所以有一个等价的**专用公式**：

$$\chi^2 = \frac{(ad - bc)^2 \, n}{(a+b)(c+d)(a+c)(b+d)}$$

它以 $n$ 和四个边际和为分母，只用四个基本数据，算得快，结果与基本公式**完全相同**（上面那个例子里 $ad - bc = 45 \times 20 - 15 \times 20 = 600$，代入得 $\chi^2 = 600^2 \times 100 / (60 \times 40 \times 65 \times 35) = 6.593$，对上了）。在动手写代码之前，先按下面的**三步**把框架搭好：

1. **建立检验假设，确定检验水准。** 两样本率比较时 $H_0$ 写「两总体率相等」（$\pi_1 = \pi_2$），$H_1$ 写「两总体率不等」；$\alpha$ 常取 0.05（双侧）。
2. **计算检验统计量。** 先算理论频数 $T_{RC} = n_R n_C / n$，再**根据 $n$ 和最小理论频数选公式**算 $\chi^2$，写出自由度。
3. **确定 $P$ 值，作出推断。** 查 $\chi^2$ 界值表或由软件给出 $P$：$P > \alpha$ 不拒绝 $H_0$（差异无统计学意义，**只能说「尚不能认为两总体率不同」**）；$P \le \alpha$ 拒绝 $H_0$、接受 $H_1$（差异有统计学意义）。

### 连续性校正：什么时候必须用

$\chi^2$ 分布是**连续型**分布，界值表也是按连续分布的理论公式算出来的；而两个率比较的原始数据是**数出来的个数**，本质上是离散的。用连续分布去近似离散资料，公式里天然带着近似误差。

误差在小样本时表现为：**算出来的 $\chi^2$ 偏大，$P$ 值偏小**，于是本该不拒绝 $H_0$ 的时候拒绝了 $H_0$——**第 I 类错误（假阳性）的概率被人为抬高**。为此要「往回拉一点」，把每个格子偏离期望的量各减去 0.5，这就是**连续性校正**（Yates 校正）：

$$\chi^2 = \sum \frac{(\lvert A - T \rvert - 0.5)^2}{T}$$

四格表专用公式也有对应的校正形式：

$$\chi^2 = \frac{(\lvert ad - bc \rvert - n/2)^2 \, n}{(a+b)(c+d)(a+c)(b+d)}$$

减 0.5 的效果不是修修补补，有时会**把结论整个翻过来**。

::: details 一个结论被翻过来的例子
某研究 A 组 30 人中 4 人有效、B 组 20 人中 1 人有效。$n = 50 \ge 40$，四个理论频数分别是 3、27、2、18——有两个落在 $1 \le T < 5$ 里，**不该直接套专用公式**。

- 不校正：$\chi^2 = 0.926$，$P = 0.336$；
- 校正后：$\chi^2 = 0.231$，$P = 0.630$。

本例两个结论都是「不拒绝 $H_0$」，差别只体现在 $\chi^2$ 上。但换成下面这种极端情形，方向就反了：某四格表 $n = 35$、最小理论频数只有 0.17（$T < 1$），此时专用公式给出 $\chi^2 = 4.646$、$P = 0.031$，看起来「有统计学意义」；而 Fisher 确切概率法给出的 $P = 0.166$。**该用 Fisher 的时候硬算 $\chi^2$，结论就是错的。**
:::

### 判据表：四格表到底用哪个方法

这是本章最该背下来的一张表。判断依据只有两个：**总例数 $n$**，以及**最小的理论频数 $T_{\min}$**（$T$ 不是数出来的，要按 $H_0$ 算出来以后取最小值）。

| 条件 | 用什么 | 手算公式 | 在 R 里怎么写 |
| --- | --- | --- | --- |
| $n \ge 40$，且所有 $T \ge 5$ | 基本公式或专用公式，**不校正** | 基本公式、专用公式 | `chisq.test(tab, correct = FALSE)` |
| $n \ge 40$，且有 $1 \le T < 5$ | **连续性校正** | 校正的基本公式、校正的专用公式 | `chisq.test(tab)`（默认就是校正） |
| $n < 40$（不论 $T$ 多好） | **Fisher 确切概率法** | 超几何分布直接算概率 | `fisher.test(tab)` |
| 有任一格 $T < 1$（不论 $n$ 多大） | **Fisher 确切概率法** | 同上 | `fisher.test(tab)` |
| 任何四格表 | Fisher 都用得上，只是 $n$ 大时计算量大 | — | `fisher.test(tab)` |

读表时注意三点：

- **两个条件是「或」的关系**：$n < 40$ 就足以让你放弃 $\chi^2$，哪怕每个 $T$ 都大于 5；反过来只要有 $T < 1$，$n$ 再大也不能算 $\chi^2$。
- **$1 \le T < 5$ 是「有格子落在里面」**，不要求全部格子都小。只要有一个格子落在 $1$ 到 $5$ 之间，就整张表改用校正公式。
- **不要只看 $T$ 平均值。** 决定公式的是最小值，一个很小的 $T$ 就足以毁掉整个 $\chi^2$ 的分布近似。

### Fisher 确切概率法

Fisher 确切概率法（Fisher's exact probability test）不属于 $\chi^2$ 检验的范畴，但它是 $\chi^2$ 检验最重要的补充。它的思路是：**固定四格表的周边合计数不动**，让表内的 $a$、$b$、$c$、$d$ 在所有可能取值上变动，把每一种组合的概率都算出来，再把「现有样本的概率」以及「比它更极端的所有组合的概率」加起来，直接得到 $P$ 值。每种组合的概率服从**超几何分布**：

$$P = \frac{(a+b)!\,(c+d)!\,(a+c)!\,(b+d)!}{a!\,b!\,c!\,d!\,n!}$$

组合的个数等于「最小周边合计数 $+ 1$」：只让一个格子的数从 0 开始每次加 1，一直加到它等于最小周边合计，其余的格子就被周边合计唯一确定了。

双侧检验和单侧检验的算法不同：现有样本的两个率之差记为 $p_1 - p_2$，**双侧**要把「比现有样本更极端」的两侧组合都算进去（即所有 $\lvert p_1 - p_2 \rvert$ 不小于现有差值的组合概率之和），**单侧**只取一侧。所以同一个四格表，单侧 $P$ 总是小于双侧 $P$——报结论时必须写清楚用的是哪一种。

适用范围上有一个很宽松的结论：**任何四格表都可以用 Fisher 确切概率法**，无论 $n$ 和 $T$ 是多少；它在小样本时是唯一正确的选择，在大样本时与 $\chi^2$ 结论一致，只是计算量大。此外，当 $\chi^2$ 检验算出的 $P$ 值**紧贴检验水准**（比如 $P = 0.048$、$0.052$）时，也建议用 Fisher 复核一下，免得结论被近似误差带偏。

### 行 × 列表资料的 $\chi^2$ 检验

当分组变量或结局变量超过两个水平（三组药、四个血型、四个临床分期），四格表就扩展成**行 × 列表**（$R \times C$ 列联表）。理论频数公式和基本公式形式不变，只是下标多了：

$$T_{ij} = \frac{n_{Ri} \, n_{Cj}}{n}, \qquad \chi^2 = \sum_{i=1}^{R}\sum_{j=1}^{C}\frac{(A_{ij}-T_{ij})^2}{T_{ij}}, \qquad \nu = (R-1)(C-1)$$

逐格算 $T$ 太慢，于是也有一个只用到实际频数的**专用公式**（与基本公式等价）：

$$\chi^2 = n\left(\sum \frac{A^2}{n_R \, n_C} - 1\right)$$

**假设怎么写，是行 × 列表最容易被判错的地方。** 三个样本率比较时：

- $H_0$：三个总体率相等，$\pi_1 = \pi_2 = \pi_3$；
- $H_1$：三个总体率**不全相同**。

$H_1$ **不能**写成 $\pi_1 \ne \pi_2 \ne \pi_3$。与 $H_0$ 对立的情况其实有四种——$\pi_1 \ne \pi_2 \ne \pi_3$、$\pi_1 \ne \pi_2 = \pi_3$、$\pi_1 = \pi_3 \ne \pi_2$、$\pi_1 = \pi_2 \ne \pi_3$，共同点是「至少有两个总体率不等」，而 $\pi_1 \ne \pi_2 \ne \pi_3$ 这种写法在数学上只覆盖了第一种，还把「甲乙不同、乙丙不同、但甲丙相同」这种明明属于 $H_1$ 的情形排除在外了。

**结论也只能说「不全相同」。** 拒绝 $H_0$ **不等于**每两组之间都有差别。上例三组有效率 84%、76%、32%，$\chi^2 = 34.03$、$\nu = 2$、$P < 0.001$，只能得出「三种方案的有效率不全相同」；至于究竟是哪两组不同，必须做**两两比较**（下一节）。直接把三个率从大到小排一遍、说「甲最好、乙次之、丙最差」是这一步最常见的错误。

**行 × 列表的适用条件**比四格表宽松一些，但也有硬线：

- 允许有**不超过 1/5 的格子**理论频数落在 $1 \le T < 5$；
- **不能有任何一个格子的 $T < 1$**。

一旦越过这两条线，有三种处理办法：

1. **增加样本含量**——$T$ 与 $n$ 成正比，多收病例是最根本的办法（也说明这件事应该在设计阶段就算清楚）；
2. **把理论频数太小的行或列与性质相近的邻行、邻列合并**——合并后 $T$ 变大，但合并要有专业意义（比如把「I 期」和「II 期」合成一组是合理的，把「I 期」和「IV 期」合并就毫无道理），而且**合并后自由度要重新算**；
3. **删去**理论频数太小的格子所对应的行或列。

后两种办法都会损失信息，还可能破坏样本的随机性，所以要谨慎——**最好的对策是在设计阶段就把样本含量留够**。

### 多个样本率的两两比较

行 × 列表 $\chi^2$ 检验拒绝 $H_0$ 之后，若想知道具体是哪两组有差别，就要做两两比较。做法是**把 $R \times C$ 表拆成若干个 $2 \times C$ 表**（或者进一步拆成若干个四格表），对每个小表单独做 $\chi^2$ 检验。

但这里有一个陷阱：$k$ 组两两比较总共要做 $\binom{k}{2}$ 次检验，**每做一次就多一次犯 I 类错误的机会**，如果每次都用 $\alpha = 0.05$，全部比较做完以后总的假阳性率会远远超过 0.05——各组之间本来没有差别，也会被「比较」出一两个有统计学意义的差别来。为了让**总的** I 类错误率仍然控制在 $\alpha = 0.05$，每次检验的水准要收紧：

$$\alpha' = \frac{2\alpha}{k(k-1)}$$

$k$ 是比较的组数。这个式子其实就是在做 Bonferroni 校正：$k$ 组两两比较共有 $k(k-1)/2$ 对，所以 $\alpha' = \alpha \big/ \frac{k(k-1)}{2} = \frac{2\alpha}{k(k-1)}$。三组比较时 $\alpha' = 0.05/3 = 0.0167$，即**每个四格表 $\chi^2$ 检验都要拿 0.0167 当水准**，$P < 0.0167$ 才算有统计学意义。

仍用上面三组方案的例子（有效率 84%、76%、32%），$\alpha' = 0.0167$：

| 对比组 | $\chi^2$ | $P$ | 判断 |
| --- | --- | --- | --- |
| 甲药 vs 乙药 | 1.000 | 0.317 | 无统计学意义 |
| 甲药 vs 丙药 | 27.750 | $1.38 \times 10^{-7}$ | 有统计学意义 |
| 乙药 vs 丙药 | 19.485 | $1.01 \times 10^{-5}$ | 有统计学意义 |

于是结论是：甲药与乙药的疗效差别无统计学意义，但两者都优于丙药。「不全相同」到这里才落地成一句说得清楚的话。

<ClickAnswer>

**想一想**：三组率比较，整体 $\chi^2$ 检验 $P = 0.30$（不拒绝 $H_0$），还能不能去做两两比较，指望从中挖出一对「有统计学意义」的差别？

---

不能。整体检验不拒绝 $H_0$，说明**没有足够证据说这几个总体率不全相同**，此时再去两两比较属于「没有假设就找差异」，是典型的多重比较滥用：拆得越细、比较次数越多，越容易碰上一个 $P < 0.05$ 的比较。而且正规的两两比较也应该在整体检验有统计学意义**之后**才做，$\alpha'$ 的调整正是为了压住这种「找出来的差别」。

需要注意的是，两两比较的结论与整体检验的结论**并不必然一致**，这是因为整体检验是把所有组的信息放在一起、只用了一个 $\alpha$；两两比较是分成若干个小表、各自用更严的 $\alpha'$。两者回答的问题不完全相同，写报告时应以研究目的为准，而不是挑对自己有利的那个。

</ClickAnswer>

### 配对四格表（McNemar）的 $\chi^2$ 检验

**配对设计**指的是同一个观察单位同时接受两种处理（或两种检测方法）。这时数据不是两组人，而是**同一批人的两种结果**，整理成四格表后每一格的来历都不同：

| | 乙法 + | 乙法 − | 合计 |
| --- | --- | --- | --- |
| 甲法 + | $a$（两法都阳） | $b$（甲阳乙阴） | $a+b$ |
| 甲法 − | $c$（甲阴乙阳） | $d$（两法都阴） | $c+d$ |
| 合计 | $a+c$ | $b+d$ | $n$ |

甲法的阳性率是 $\frac{a+b}{n}$，乙法的阳性率是 $\frac{a+c}{n}$。要让两者相等，只需要 $b = c$——**$a$ 和 $d$ 是两种方法结论一致的部分，它们同时出现在两个率里、互相抵消了**。所以判断两种方法有没有差别，看的就是那两个「不一致」的格子 $b$ 和 $c$ 相不相等：

- $H_0$：$B = C$（总体中两种方法阳性率相同）
- $H_1$：$B \ne C$

注意总体用大写 $B$、$C$，样本用小写 $b$、$c$。若 $H_0$ 成立，$b$ 和 $c$ 对应的理论频数都应该是 $(b+c)/2$，把这两个格子代入基本公式化简，就得到**配对 $\chi^2$ 检验**（McNemar 检验）的专用公式：

$$\chi^2 = \frac{(b-c)^2}{b+c}, \qquad \nu = 1$$

当 $b + c < 40$ 时要校正：

$$\chi^2 = \frac{(\lvert b - c \rvert - 1)^2}{b+c}$$

$b + c \ge 40$ 用不校正的式子，$b + c < 40$ 用校正的式子——这里的判断标准和四格表的 $n$ 是**同一个意思**，只不过配对资料的有效信息只来自不一致的那 $b+c$ 个个体，所以拿 $b+c$ 而不是 $n$ 当样本含量。

::: danger 配对资料不能用普通四格表 $\chi^2$ 检验
同样的数据、同样的四格表，**普通 $\chi^2$ 检验和 McNemar 检验回答的是两个不同的问题**：

- **McNemar 检验**：两种方法（两种处理）的**阳性率有没有差别**——只用到 $b$ 和 $c$，即检验「有没有系统性的不一致」；
- **普通四格表 $\chi^2$ 检验**：两个变量之间**有没有关联**——用到全部四个格子，即检验「甲法和乙法的结果是不是相互独立」。

同一份配对资料，两种算法可以给出相差近 10 倍的 $P$ 值（$P = 0.0053$ 对 $P = 0.00055$），在小样本、结论紧贴 0.05 时完全可以一个显著、一个不显著。所以拿到资料第一件事是**看清设计方案**：完全随机设计的两组用四格表 $\chi^2$ 检验；同一个体先后/同时接受两种处理的配对设计，比较差别用 McNemar 检验，分析关联才用普通四格表 $\chi^2$。用错了，结论就不可信。

还有一点：配对表做相关性分析时，**必须把资料整理成配对设计的表格形式**，不能按成组资料去摆；如果检验出两种处理之间确有相关，还应进一步计算列联系数来描述相关的强弱。
:::

### $\chi^2$ 检验的使用条件

把散落在各节的限制汇成一张清单，做题时按顺序过一遍：

**一、看资料类型和设计，别选错方法。**

| 资料类型 | 目的 | 该用的方法 |
| --- | --- | --- |
| 完全随机设计，两组，二分类结局 | 两总体率有无差别 | 四格表 $\chi^2$ 检验（按判据表选公式或 Fisher） |
| 完全随机设计，多组，二分类结局 | 多个总体率有无差别 | 行 × 列表 $\chi^2$ 检验 + 两两比较 |
| 完全随机设计，多组，多分类结局 | 多个总体构成比有无差别 | 行 × 列表 $\chi^2$ 检验 |
| 配对设计（同一个体两种处理），二分类 | 两种处理有无差别 | **配对 $\chi^2$ 检验（McNemar）** |
| 配对设计，二分类 | 两种处理有无关联 | 普通四格表 $\chi^2$ 检验（专用公式） |
| 一份样本，一个分类变量 | 频数分布是否符合某理论分布 | 拟合优度 $\chi^2$ 检验 |
| 两变量均为有序，属性不同 | 有无线性变化趋势 | 线性趋势 $\chi^2$ 检验 |

**二、看理论频数够不够用。**

- 四格表：$n \ge 40$ 且所有 $T \ge 5$ 才可以直接用；有 $1 \le T < 5$ 要校正；$n < 40$ 或有 $T < 1$ 必须用 Fisher。
- 行 × 列表：允许不超过 1/5 的格子有 $1 \le T < 5$，**不许有 $T < 1$**。不合条件就增加样本含量、合并相邻行列（合并后有专业意义、自由度重算）或删除行列。

**三、看变量是不是「有序」，别把等级资料当无序处理。**

- 若分析变量是**等级资料**（治愈、显效、有效、无效），而分组变量无序，这张表是**单向有序** $R \times C$ 表。此时 $\chi^2$ 检验是「浪费信息」的做法：**任意调换两列数据的顺序，$\chi^2$ 值一点都不会变**，因为它只数个数、不管顺序；可等级里的「程度」信息恰恰就藏在顺序里。这类资料应当用**秩和检验**或 Ridit 分析。
- 若**两个变量都是有序的、但属性不同**（如年龄分组与晶状体混浊程度），则要按研究目的分流：分析**有无差别**→ 视为单向有序表用秩和检验；分析**有无相关**→ 等级相关或积差相关；分析**有无线性趋势**→ 线性趋势 $\chi^2$ 检验。

### 拟合优度与线性趋势（$\chi^2$ 的两个延伸用法）

$\chi^2$ 检验不只用于「比较率」，它还能回答另外两类问题。

**拟合优度 $\chi^2$ 检验（goodness of fit）**：判断一份样本的**频率分布是否符合某个给定的理论分布**（正态分布、二项分布、Poisson 分布等）。做法是把数据分区间列出频数表，按假设的理论分布算出每组的**理论频数 $T$**，代入基本公式求和：

$$\chi^2 = \sum \frac{(A-T)^2}{T}, \qquad \nu = \text{组数} - \text{计算 } T \text{ 时所用参数的个数}$$

注意自由度**不是**组数减 1：正态分布有 $\mu$ 和 $\sigma^2$ 两个参数，若用样本均数和标准差去估计它们，就要再减 2。另外，$\chi^2$ 检验要求 $T$ 不能太小，所以频数表两端 $T < 5$ 的组段要合并，合并后组数相应减少。正态性检验只适用于正态分布，而拟合优度检验的思路可以套到任何指定的理论分布上。

**线性趋势 $\chi^2$ 检验**：当两个变量都是有序的，问「有没有随等级升高而单调变化的趋势」。基本思想是把行 × 列表的总 $\chi^2$ **分解**成两个分量：

$$\chi^2_{\text{总}} = \chi^2_{\text{回归}} + \chi^2_{\text{偏离}}, \qquad \nu_{\text{总}} = \nu_{\text{回归}} + \nu_{\text{偏离}}$$

具体做法是先给两个有序变量从小到大赋值（1、2、3……），算线性回归系数 $b$ 及其方差 $S_b^2$，则

$$\chi^2_{\text{回归}} = \frac{b^2}{S_b^2}, \qquad \nu_{\text{回归}} = 1$$

偏离线性回归的分量用减法得到：$\chi^2_{\text{偏离}} = \chi^2_{\text{总}} - \chi^2_{\text{回归}}$，$\nu_{\text{偏离}} = \nu_{\text{总}} - 1$。读结果时：

- **线性回归分量有统计学意义、偏离分量无统计学意义** → 两个变量不仅相关，而且是**简单的直线关系**；
- **两个分量都有统计学意义** → 两个变量确实相关，但关系**不是简单的直线关系**（还可能弯曲、还可能变化得不均匀）。

这也是 $\chi^2$ 可加性的直接用处：两个独立 $\chi^2$ 变量相加，自由度也相加。

## 在 R 里怎么做

R 里做本章全部检验的主力函数只有三个：`chisq.test()`、`fisher.test()`、`mcnemar.test()`。它们都吃**矩阵或表**，所以第一步永远是先把频数整理成一张列联表。下面全部使用 R **自带**的数据集，复制粘贴就能跑。

### 一、四格表：先看理论频数，再决定用哪个

`UCBAdmissions` 是 R 自带的一份录取数据（行 = 录取结果，列 = 性别，第三维 = 系），取其中一个系就是一张标准的四格表：

```r
# 取 A 系：行 = 录取结果，列 = 性别
tab <- UCBAdmissions[, , "A"]
tab
#>           Gender
#> Admit      Male Female
#>   Admitted  512     89
#>   Rejected  313     19

# 第一步：算理论频数（H0 成立时的期望人数），判断该用哪个公式
round(chisq.test(tab)$expected, 2)
#>           Gender
#> Admit          Male   Female
#>   Admitted 531.43  69.57
#>   Rejected 293.57  38.43

sum(tab)                    # n = 933，≥ 40
min(chisq.test(tab)$expected)  # 38.43，所有 T ≥ 5
```

$n = 933 \ge 40$、$T_{\min} = 38.43 \ge 5$，按判据表**不该校正**，要用专用公式（等价于 `correct = FALSE`）：

```r
chisq.test(tab, correct = FALSE)   # 专用公式：不校正
#> X-squared = 17.248, df = 1, p-value = 3.28e-05

chisq.test(tab)                    # 默认就是 Yates 校正 —— 本例不该用
#> X-squared = 16.372, df = 1, p-value = 5.205e-05

fisher.test(tab)                   # Fisher 任何时候都能用
#> p-value = 1.669e-05
```

输出怎么读：

- `X-squared` 是 $\chi^2$ 值，`df` 是自由度，`p-value` 是 $P$ 值。$P < 0.05$，拒绝 $H_0$，可认为该系男女的录取率不同——把 `$expected` 与 `$observed` 对照可以看出，女性是「录取人数多于期望」（**女性录取率反而更高**，82.4% 对 62.1%）。这正是**关联的方向要在检验之外自己看**的典型例子。
- **`chisq.test()` 对 2×2 表默认 `correct = TRUE`**，也就是无条件用 Yates 校正。但按本章的判据，$n \ge 40$ 且所有 $T \ge 5$ 时**不该校正**——所以拿到四格表，习惯上先算 `$expected` 判断，再决定要不要显式写 `correct = FALSE`。三个方法的 $P$ 值分别约为 $3.28 \times 10^{-5}$、$5.21 \times 10^{-5}$、$1.67 \times 10^{-5}$，量级一致，本例结论不受影响；但 $P$ 值紧贴 0.05 时，这个选择足以改变结论。
- `correct` 参数只对 2×2 表有效，$R \times C$ 表会自动忽略它。

### 二、把判据表写成函数

与其每次手算，不如把判据写成一个小函数，喂一张四格表进去，让它告诉你该用哪个：

```r
decide <- function(tab) {
  e <- suppressWarnings(chisq.test(tab)$expected)  # 会警告，属于正常现象
  n <- sum(tab)
  tmin <- min(e)
  if (n < 40 || tmin < 1) {
    paste0("Fisher 确切概率法  (n = ", n, ", Tmin = ", round(tmin, 2), ")")
  } else if (tmin < 5) {
    paste0("连续性校正  (n = ", n, ", Tmin = ", round(tmin, 2), ")")
  } else {
    paste0("不校正  (n = ", n, ", Tmin = ", round(tmin, 2), ")")
  }
}

decide(matrix(c(45, 15, 20, 20), 2, byrow = TRUE))  # 不校正  (n = 100, Tmin = 14)
decide(matrix(c(4, 26, 1, 19), 2, byrow = TRUE))    # 连续性校正  (n = 50, Tmin = 2)
decide(matrix(c(13, 2, 7, 8), 2, byrow = TRUE))     # Fisher  (n = 30, Tmin = 5)
decide(matrix(c(9, 1, 4, 6), 2, byrow = TRUE))      # Fisher  (n = 20, Tmin = 3.5)
decide(matrix(c(1, 31, 1, 2), 2, byrow = TRUE))     # Fisher  (n = 35, Tmin = 0.17)
decide(UCBAdmissions[, , "A"])                      # 不校正  (n = 933, Tmin = 38.43)
```

第二行值得特别注意：**$n = 50 \ge 40$，但 $T_{\min} = 2$ 落在 $1 \le T < 5$**，所以要校正。第三行是另一种情况：**$T_{\min} = 5$ 明明够大，但 $n = 30 < 40$**，一样要用 Fisher。这两条岔路恰好把判据表的「或」关系讲全了。

### 三、校正与 Fisher：公式换了，结论也会换

```r
# 情形 1：n ≥ 40，但有 1 ≤ T < 5 → 校正
tab2 <- matrix(c(4, 26, 1, 19), nrow = 2, byrow = TRUE,
               dimnames = list(c("A组", "B组"), c("有效", "无效")))
addmargins(tab2)
#>     有效 无效 Sum
#> A组    4   26  30
#> B组    1   19  20
#> Sum    5   45  50

round(chisq.test(tab2)$expected, 2)   # 3, 27 / 2, 18 —— 有两格 1 ≤ T < 5
chisq.test(tab2, correct = FALSE)     # 0.9259, p = 0.3359
chisq.test(tab2)                      # 0.2315, p = 0.6304  ← 校正后

# 情形 2：n < 40 → Fisher（哪怕 T 全都够大）
tab3 <- matrix(c(13, 2, 7, 8), nrow = 2, byrow = TRUE)
round(chisq.test(tab3)$expected, 2)   # 10, 5 / 10, 5 —— 都 ≥ 5，但 n = 30
chisq.test(tab3, correct = FALSE)     # 5.400, p = 0.0201
chisq.test(tab3)                      # 3.750, p = 0.0528
fisher.test(tab3)                     # p = 0.0502  ← 该报这个

# 情形 3：有格子 T < 1 → 必须 Fisher
tab4 <- matrix(c(1, 31, 1, 2), nrow = 2, byrow = TRUE)
round(chisq.test(tab4)$expected, 2)   # 1.83, 30.17 / 0.17, 2.83 —— 有一格 0.17
chisq.test(tab4, correct = FALSE)     # 4.646, p = 0.0311  ← 完全不可信
fisher.test(tab4)                     # p = 0.1664  ← 唯一正确的答案
```

情形 2 是最有教育意义的一例：不校正的 $\chi^2$ 给出 $P = 0.020$（有统计学意义），校正后 $P = 0.053$（无统计学意义），Fisher 给出 $P = 0.0502$。**同一张表、同一批数据，换个公式就能让结论正反面翻转**，这就是判据表存在的理由。

再注意两点：

- `chisq.test()` 在期望频数太小时会打印警告 `Chi-squared approximation may be incorrect`。**这个警告不是错误，是提醒**——它在告诉你「你刚才那一步可能不该用 $\chi^2$」。看到它就回头查判据表。
- 情形 3 里，$\chi^2 = 4.646$、$P = 0.031$ 看上去很漂亮，但它是**错的**：一格理论频数只有 0.17，连续分布的近似彻底失效了。

### 四、行 × 列表

`HairEyeColor` 是 R 自带的 592 人头发颜色、眼睛颜色、性别数据。先做一张 4×4 的头发色 × 眼睛色表，问「头发颜色和眼睛颜色有没有关联」：

```r
tab5 <- margin.table(HairEyeColor, c(1, 2))   # 4×4：行 = 头发色，列 = 眼睛色
tab5
#>        Eye
#> Hair    Brown Blue Hazel Green
#>   Black    68   20    15     5
#>   Brown   119   84    54    29
#>   Red      26   17    14    14
#>   Blond     7   94    10    16

sum(tab5)                                  # n = 592
min(chisq.test(tab5)$expected)             # 7.68 —— 最小理论频数够大
sum(chisq.test(tab5)$expected < 5)         # 0 —— 没有格子 T < 5

chisq.test(tab5)
#> X-squared = 138.29, df = 9, p-value < 2.2e-16
```

`df = 9` 正是 $(4-1)(4-1) = 9$。$P < 0.001$，拒绝 $H_0$，可认为头发颜色与眼睛颜色不独立。`tab5` 的 16 个格子里没有一个 $T < 5$，$T_{\min} = 7.68$，条件满足，可以放心用。

**换成分层数据，同一个数据集立刻就出问题：**

```r
chisq.test(HairEyeColor[, , "Male"])
#> Warning: Chi-squared approximation may be incorrect
#> X-squared = 41.28, df = 9, p-value = 4.45e-06

min(chisq.test(HairEyeColor[, , "Male"])$expected)   # 4.02 —— 有 1 格 T < 5
```

男性这张表 $n = 279$、$T_{\min} = 4.02$，16 格里恰好 1 格低于 5（比例 $1/16 < 1/5$，勉强过关），所以 R 只是警告、没有报错，结果仍可参考；如果低理论频数的格子超过 $1/5$，就该合并类别或换 Fisher 了。**`margin.table()` 的作用是按指定维度求边际和**——`margin.table(HairEyeColor, c(1, 2))` 把性别维度合掉，得到男女合计的 4×4 表；这正是「合并相邻行列」在 R 里的写法。

### 五、多个率的两两比较

`chisq.test()` 只管整体，两两比较要自己循环拆表。关键是**把检验水准也一起改掉**：

```r
tab6 <- matrix(c(42,  8,
                 38, 12,
                 16, 34), nrow = 3, byrow = TRUE,
               dimnames = list(c("甲药", "乙药", "丙药"), c("有效", "无效")))
addmargins(tab6)
#>       有效 无效 Sum
#> 甲药    42    8  50
#> 乙药    38   12  50
#> 丙药    16   34  50
#> Sum     96   54 150

chisq.test(tab6, correct = FALSE)     # 整体检验：34.028, df = 2, p = 4.083e-08

k <- nrow(tab6)
alpha <- 0.05 / choose(k, 2)          # α' = 0.05/3 = 0.0167
alpha

for (i in 1:(k - 1)) {
  for (j in (i + 1):k) {
    sub <- tab6[c(i, j), ]            # 拆成四格表
    p <- chisq.test(sub, correct = FALSE)$p.value
    cat(rownames(tab6)[i], "vs", rownames(tab6)[j],
        " chi2 =", round(chisq.test(sub, correct = FALSE)$statistic, 3),
        " p =", format.pval(p, digits = 3),
        ifelse(p < alpha, "  有统计学意义", "  无统计学意义"), "\n")
  }
}
#> 甲药 vs 乙药  chi2 = 1  p = 0.317  无统计学意义
#> 甲药 vs 丙药  chi2 = 27.75  p = 1.38e-07  有统计学意义
#> 乙药 vs 丙药  chi2 = 19.485  p = 1.01e-05  有统计学意义
```

`choose(k, 2)` 就是 $\binom{k}{2} = k(k-1)/2$，和公式 $\alpha' = \frac{2\alpha}{k(k-1)}$ 完全等价。结论：甲药与乙药差别无统计学意义，两者都优于丙药。**注意这里是先做整体检验、再做两两比较**，顺序不能颠倒。

### 六、配对四格表：McNemar 检验

```r
# 同一批样本分别用甲法、乙法检测，只有"两法不一致"的格子进检验
paired <- matrix(c(45, 25,
                    8, 22), nrow = 2, byrow = TRUE,
                 dimnames = list(甲法 = c("阳性", "阴性"),
                                 乙法 = c("阳性", "阴性")))
paired
#>       乙法
#> 甲法   阳性 阴性
#>   阳性   45   25
#>   阴性    8   22

b <- paired[1, 2]      # 甲阳乙阴
c_ <- paired[2, 1]     # 甲阴乙阳（不要用 c 当变量名，会盖掉 c() 函数）
b + c_                 # 33 —— 小于 40，要校正

mcnemar.test(paired)                   # 默认带校正：本例该用
#> McNemar's chi-squared = 7.7576, df = 1, p-value = 0.005349

mcnemar.test(paired, correct = FALSE)  # 不校正
#> McNemar's chi-squared = 8.7576, df = 1, p-value = 0.003083

# 同一张表，若问"两种方法的结果有没有关联"，用普通四格表卡方
chisq.test(paired, correct = FALSE)
#> X-squared = 11.931, df = 1, p-value = 0.0005522
```

读法：

- `mcnemar.test()` **默认 `correct = TRUE`**，对应公式 $\chi^2 = \frac{(\lvert b-c \rvert-1)^2}{b+c}$。这里 $b + c = 33 < 40$，正是该校正的情形，所以直接用默认值就对。
- 若 $b + c \ge 40$（本例改成 `matrix(c(60, 14, 30, 16), ...)` 则 $b+c = 44$），按判据应当**不校正**，此时要显式写 `mcnemar.test(paired, correct = FALSE)`：不校正 $\chi^2 = 5.818$、$P = 0.0159$；默认校正后 $\chi^2 = 5.114$、$P = 0.0237$。两个都拒绝 $H_0$，但报数时应当报与判据相符的那个。
- 三种算法给出三个 $P$：$0.0053$（McNemar 校正）、$0.0031$（McNemar 不校正）、$0.00055$（普通 $\chi^2$ 关联检验）。**它们回答的不是同一个问题**——最后一个问的是「甲乙两法的结果是否独立」，$P$ 最小也不代表「两法阳性率差别最大」。设计方案决定方法，方法决定 $P$ 该怎么解释。

### 七、拟合优度与趋势

```r
# 拟合优度：Titanic 上各舱位人数是否服从某个给定的比例？
obs <- margin.table(Titanic, 1)
obs
#>  1st  2nd  3rd Crew
#>  325  285  706  885

chisq.test(obs)                              # H0：四类人数相等
#> X-squared = 467.81, df = 3, p-value < 2.2e-16

# H0：各舱位人数按 15%、13%、32%、40% 分布
chisq.test(obs, p = c(0.15, 0.13, 0.32, 0.40))
#> X-squared = 0.11284, df = 3, p-value = 0.9903
#> 期望频数：330.1 286.1 704.3 880.4
```

- 不写 `p =` 时，`chisq.test()` 默认检验「各类别概率相等」，自由度是 $k - 1 = 3$。
- 写了 `p =` 就变成**拟合优度检验**：观测比例是 14.8%、12.9%、32.1%、40.2%，与给定的 15%、13%、32%、40% 差别无统计学意义（$P = 0.99$），数据与这份分布假设相容。
- 若理论分布是正态分布、Poisson 分布等带有**未知参数**的分布，参数要先用样本估计，自由度还要再减去估计的参数个数——`chisq.test()` 不会替你算这个，得自己写 `df`。

```r
# 线性趋势：把舱位当有序等级（1st → 3rd），问生还率是否单调变化
tab7 <- margin.table(Titanic, c(1, 4))[c("1st", "2nd", "3rd"), ]
tab7
#>       Survived
#> Class   No Yes
#>   1st  122 203
#>   2nd  167 118
#>   3rd  528 178

chisq.test(tab7, correct = FALSE)                    # 整体关联
#> X-squared = 133.05, df = 2, p-value < 2.2e-16

prop.trend.test(tab7[, "Yes"], rowSums(tab7), score = 1:3)   # 趋势分量
#> X-squared = 132.51, df = 1, p-value < 2.2e-16
```

三个舱位的生还率是 62.5%、41.4%、25.2%，单调下降。$\chi^2_{\text{总}} = 133.05$（$\nu = 2$）分解成 $\chi^2_{\text{回归}} = 132.51$（$\nu = 1$）与 $\chi^2_{\text{偏离}} = 0.54$（$\nu = 1$）。回归分量占了绝大部分、偏离分量不到 1（$P > 0.05$），说明生还率与舱位等级之间不只是「有关联」，而且是**接近直线的单调趋势**。

`prop.trend.test()` 做的是 $k$ 组率之间的线性趋势检验（Cochran–Armitage），适用于「$k$ 个有序分组 × 二分类结局」这张 $k \times 2$ 表，和本章讲的 $\chi^2$ 分解回答同一个问题、自由度也一致，但统计量的算法不同（**不要指望它和手算的 $\chi^2_{\text{回归}}$ 分毫不差**）。若两个变量都是多水平的有序变量、需要按一般 $R \times C$ 表做线性关联检验，则需要 `coin` 等扩展包里的线性关联检验。

## 容易踩的坑

- **拿到四格表就用 `chisq.test()` 默认参数。** R 对 2×2 表默认开启 Yates 校正，而按判据，$n \ge 40$ 且所有 $T \ge 5$ 时**不该校正**。正确姿势是先 `chisq.test(tab)$expected` 看 $T_{\min}$，再决定 `correct = TRUE` 还是 `FALSE`。另外 `correct` 对 $R \times C$ 表无效，别以为它在所有表上都起作用。
- **把「$n < 40$ 用 Fisher」和「$T < 5$ 用校正」混成一条。** 这是两个独立条件，满足任何一个就要升级处理：$n = 30$、$T$ 全部大于 5 时仍然要用 Fisher（因为有效样本量太小）；$n = 933$、却有一格 $T = 0.5$ 时也必须用 Fisher（因为近似失效）。判断公式时同时看 $n$ 和 $T_{\min}$，谁不达标都算不达标。
- **看到 R 的 `Chi-squared approximation may be incorrect` 警告当作没看见。** 这不是报错，是 R 在提醒「理论频数太小、$\chi^2$ 近似不可靠」。带着这个警告往下报 $P$ 值是错的——回头查 `$expected`，该校正就校正，该 Fisher 就 Fisher。
- **用普通四格表 $\chi^2$ 检验分析配对资料。** 同一个体先后接受两种检查，数据表格看起来和成组四格表一模一样，但每一格的来历完全不同。此时比较两种方法有无差别要用 McNemar 检验（只看 $b$、$c$），普通 $\chi^2$ 检验回答的是「有无关联」。两种算法能给出相差近 10 倍的 $P$ 值。拿到资料先问：这四格是**两批人**还是**同一批人的两个结果**？
- **多组率比较拒绝 $H_0$ 后直接排序下结论。** 行 × 列表 $\chi^2$ 检验的 $H_1$ 是「各总体率**不全相同**」，$P < 0.05$ 只说明「至少有两个不相等」，绝不等于每两组都有差别。要么做两两比较（并把 $\alpha' = \frac{2\alpha}{k(k-1)}$ 一起改掉），要么如实写「不全相同」。顺带一提，$H_1$ 写成 $\pi_1 \ne \pi_2 \ne \pi_3$ 也是错的。
- **把等级资料强行做 $\chi^2$ 检验。** 结局是「治愈/显效/有效/无效」时，等级里带着「程度」信息，而 $\chi^2$ 只数个数：**任意调换两列的顺序，$\chi^2$ 值都不变**。这类单向有序资料应当用秩和检验。同理，两个变量都有序、属性不同时，要按目的分流到秩和检验、等级相关或线性趋势检验，而不是一律上 $\chi^2$。
- **理论频数用观察比例反推。** $T$ 只能在 $H_0$ 成立的假设下算：拿**合计率**去乘各组的例数（$T_{RC} = n_R n_C / n$）。用各组实际有效率去乘，算出来的就是 $A$ 而不是 $T$，$\chi^2$ 必然是 0。软件里的 `$expected` 就是这个 $T$，可以直接取用。

## 和别的课怎么对上

::: tip 相关章节
- **[《信息技术基础》第 13 讲 同分布检验与列联表检验](/intro-it/13-goodness-of-fit-and-contingency)**—— **这一讲与本章是同一件事的两面，建议连着看。** 那一讲是从 R 出发的**实操**：怎么用 `table()`、`margin.table()`、`addmargins()` 把原始数据整理成列联表，怎么调 `chisq.test()`、`fisher.test()`、`mcnemar.test()` 并读懂输出。本章讲的是这些函数背后的**原理与适用条件**：$\chi^2$ 为什么是 $\sum (A-T)^2/T$、自由度为什么是 $(R-1)(C-1)$、什么时候**不能**用默认参数、什么时候必须换成 Fisher。代码会写不等于结论会下——判据表和适用条件是本章补上的那一半。
- **[《医学大数据分析与决策》第 4 周 关联规则](/Medical-Big-Data-Analysis/4-association-rules)**—— 关联规则和 $\chi^2$ 独立性检验都在问「两个分类变量有没有关联」，但回答方式完全不同。
  - **$\chi^2$ 独立性检验是验证性的、整体性的**：先有 $H_0$「两个变量独立」，再把整张列联表所有格子合起来算**一个** $\chi^2$ 和**一个** $P$ 值。它回答「这两个变量独立吗、这个关联会不会只是抽样误差」，能控制 I 类错误；但它**不告诉你关联的方向和强度**——只能靠标准化残差大致看出哪个格子偏多。
  - **关联规则是探索性的、逐条的**：不设 $H_0$、不给 $P$ 值，把每个「项集组合」单独拿出来算**支持度**（这个组合在全部记录中出现的频率）、**置信度**（$A$ 出现时 $B$ 也出现的比例）、**提升度**（置信度 ÷ $B$ 的基础发生率）。提升度 $= 1$ 意味着 $A$ 与 $B$ 独立，$> 1$ 是正关联、$< 1$ 是负关联——**这里的「提升度 = 1」和「$\chi^2$ 检验不拒绝独立性假设」说的是同一件事**。
  - 简言之：**卡方给你一个 $P$ 值，关联规则给你一串规则和强度**。实际工作中两者常接力使用——先做 $\chi^2$ 独立性检验确认「这两个变量不是独立的」，再用关联规则或比值比去看具体是**哪一类跟哪一类**在一起、强度多大、支不支持「$A$ 会导致 $B$」这种说法。关联规则还擅长同时处理几十个变量、从海量组合里捞候选，而 $\chi^2$ 一次只盯一张表。
- **[《信息技术基础》第 4 讲 列表与因子](/intro-it/4-lists-and-factors)**—— 本章所有检验的**入口**都是列联表，而列联表在 R 里就是带 `dimnames` 的矩阵/数组，行列名就是因子水平。那一讲讲 `factor()` 怎么建、`levels` 怎么定顺序、`table()` 怎么清点，直接决定你的表行序对不对：**单向有序资料做检验时，等级顺序定错，秩和检验的结论就会反**。本章示例里的 `UCBAdmissions`、`HairEyeColor`、`Titanic` 都是多维数组，正是那一讲的延伸。
- **[《信息技术基础》第 12 讲 参数假设检验](/intro-it/12-hypothesis-testing)**—— 本章是假设检验框架在**计数资料**上的实例。那里立的「$H_0$ 与 $H_1$ 对立、$\alpha$ 是预先定好的犯错容忍度、$P$ 小才拒绝 $H_0$、不拒绝不等于接受 $H_0$」这套规矩在这里一字不改地照用，只是检验统计量从 $t$、$z$ 换成了 $\chi^2$。留意本章的两个「反直觉点」在那边的框架下怎么解释：**$H_1$ 写「不等」但检验是单侧的**（因为平方把两侧并到右尾），**$\chi^2$ 与 $t$ 一样都是右侧单尾查表**——那两讲的临界值查表方式在这里可以直接迁移。
- **[《信息技术基础》第 3 讲 数组与数据框](/intro-it/3-arrays-and-data-frames)**—— 本章的 `UCBAdmissions`（三维）、`HairEyeColor`（三维）、`Titanic`（四维）都是数组，`[, , "A"]`、`[, , "Male"]` 这种按下标取子集、`margin.table()` 按维度求边际和，全部依赖那一讲的数组索引知识。**求边际和正是「合并相邻行列」在 R 里的实现**。
- **[《信息技术基础》第 11 讲 参数估计](/intro-it/11-parameter-estimation)**—— 假设检验只回答「有没有差别」，不回答「差别有多大」。报告两个率比较的结果时通常还要给出**率差的置信区间**（或 `fisher.test()` 顺带输出的比值比及其置信区间），那一讲的手法是本章结论的最佳补充。本章示例里的 `fisher.test(tab)` 就额外给出了 odds ratio 的 95% 置信区间。
- **[《信息技术基础》第 9 讲 高级绘图](/intro-it/9-base-graphics)**—— 列联表光看数字不容易发现结构，`mosaicplot()`（马赛克图）能在基础绘图系统里一眼看出哪些格子的实际频数远超期望；`barplot()` 画堆叠条形图则适合展示各组的构成比。本章讲「$\chi^2$ 检验不告诉你方向」，图正好补上这一块。
- **[《医学大数据分析与决策》第 2 周 数据预处理](/Medical-Big-Data-Analysis/2-data-preprocessing)**—— 本章的「合并相邻行列以满足理论频数要求」「删除理论频数太小的行列」「检查表里有没有空格子」，在实际数据上就是那一周讲的变量分箱、类别合并与缺失值处理。区别是：那里是从数据工程角度做，本章是从统计学角度告诉你**为什么必须做、合并到什么程度才够**（不超过 1/5 的格子有 $1 \le T < 5$，且没有 $T < 1$）。
- **[《医学大数据分析与决策》第 5 周 分类（一）](/Medical-Big-Data-Analysis/5-classification-1)**—— 分类模型评估用的**混淆矩阵**是一张四格表，由它算出的准确率、灵敏度、特异度，本质上是同一批计数数据的不同「率」。本章的 $\chi^2$ 检验判断两个变量是否独立，那一周则进一步问「用一个变量预测另一个变量的效果有多好」——诊断试验的评价指标（灵敏度/特异度/Youden 指数）正是从这里长出来的。**注意别把「$\chi^2$ 检验显著」当成「预测效果好」**：大样本下一点微弱的关联也能显著，而预测价值要看灵敏度、特异度这些强度指标。
:::

<!-- 回链建议
建议在这几页回链过来（都指向 /Health-statistics/10-chi-square）：
- /intro-it/13-goodness-of-fit-and-contingency 的开头或「本讲小结」处，加一句「原理、四格表公式的判据表（何时用专用公式/校正公式/Fisher）与适用条件的完整归纳见 卫生统计学 第 10 章」。
- /intro-it/12-hypothesis-testing 讲「检验统计量与临界值」处，加一句「$\chi^2$ 统计量与自由度 $(R-1)(C-1)$ 的来历见 卫生统计学 第 10 章」。
- /intro-it/4-lists-and-factors 讲 `factor()` 与 `levels` 处，加一句「列联表的构造、有序水平顺序对检验结论的影响见 卫生统计学 第 10 章」。
- /intro-it/3-arrays-and-data-frames 讲多维数组与下标取子集处，加一句「按维度求边际和、由多维数组拆出四格表见 卫生统计学 第 10 章」。
- /intro-it/11-parameter-estimation 讲「率的置信区间」处，加一句「两个率比较的检验与比值比区间估计见 卫生统计学 第 10 章」。
- /intro-it/9-base-graphics 讲 `mosaicplot()` / `barplot()` 处，加一句「列联表的统计检验与各格偏离期望的方向见 卫生统计学 第 10 章」。
- /Medical-Big-Data-Analysis/4-association-rules 的开头或「支持度/置信度/提升度」定义附近，加一句「$\chi^2$ 独立性检验与关联规则在‘两个变量是否关联’上的异同见 卫生统计学 第 10 章」。
- /Medical-Big-Data-Analysis/2-data-preprocessing 讲「类别合并/分箱」处，加一句「合并到什么程度才满足 $\chi^2$ 检验的理论频数要求见 卫生统计学 第 10 章」。
- /Medical-Big-Data-Analysis/5-classification-1 讲「混淆矩阵与评价指标」处，加一句「混淆矩阵作为四格表的统计检验见 卫生统计学 第 10 章」。
-->

## 小结

1. **$\chi^2$ 检验的全部思想就是一个式子**：$\chi^2 = \sum \frac{(A-T)^2}{T}$，自由度 $\nu = (R-1)(C-1)$。$A$ 是数出来的实际频数，$T = n_R n_C / n$ 是 $H_0$ 成立时「应该」有的人数。两者吻合得好 $\chi^2$ 就小。因为统计量已经平方，**$\chi^2$ 检验永远是单侧（只查右尾）**，尽管 $H_1$ 写的是「不等」。
2. **四格表选公式看两个数：$n$ 和 $T_{\min}$。** $n \ge 40$ 且所有 $T \ge 5$ → 基本/专用公式不校正；$n \ge 40$ 且有 $1 \le T < 5$ → 连续性校正；$n < 40$ **或**有 $T < 1$ → Fisher 确切概率法。两个条件是「或」，满足任一即升级。**Fisher 对任何四格表都适用**，$P$ 值紧贴 0.05 时尤其值得用它复核。
3. **行 × 列表只管「不全相同」。** $H_1$ 是「各总体率不全相同」，$P < 0.05$ 只说明至少有两组不同；想知道哪两组不同必须做**两两比较**，并且把检验水准改成 $\alpha' = \frac{2\alpha}{k(k-1)}$（等价于 $\alpha / \binom{k}{2}$，三组时是 0.0167）。适用条件：不超过 1/5 的格子有 $1 \le T < 5$，且**不能有 $T < 1$**——不满足就增加样本量、合并相邻行列（要有专业意义、自由度重算）或删除行列。
4. **配对设计要用 McNemar 检验。** 同一批人的两种结果里，只有不一致的 $b$、$c$ 两个格子提供信息：$\chi^2 = \frac{(b-c)^2}{b+c}$，$b+c<40$ 时校正为 $\frac{(\lvert b-c \rvert-1)^2}{b+c}$。它检验的是「两种处理的阳性率有无差别」；同一张表做普通四格表 $\chi^2$ 检验，回答的是「两种处理的结果有无关联」。**先看清设计方案，再选方法。**
5. **在 R 里三个函数管完**：`chisq.test()`（默认对 2×2 表开启 Yates 校正，所以要先看 `$expected` 再决定 `correct = TRUE/FALSE`）、`fisher.test()`（小样本或 $T<1$ 时用它，还附送比值比的置信区间）、`mcnemar.test()`（配对资料，默认带校正）。看到 `Chi-squared approximation may be incorrect` 警告不要忽略，那是 R 在提醒你回头查判据表。
